$ErrorActionPreference = "Stop"
$BASE     = "Z:\AppFinancas"
$MEMORIA  = "$BASE\MEMORIA_PROJETO.md"
$LOG_DIR  = "$BASE\logs"
$LOG_FILE = "$LOG_DIR\16c_update_memoria.log"

if (-not (Test-Path $LOG_DIR)) { New-Item -ItemType Directory -Path $LOG_DIR -Force | Out-Null }

function Log {
    param([string]$msg, [string]$color = "White")
    $stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[$stamp] $msg"
    Write-Host $line -ForegroundColor $color
    Add-Content -Path $LOG_FILE -Value $line -Encoding utf8
}

Log "================================================================" "Cyan"
Log " SCRIPT 16c - Reescrever MEMORIA_PROJETO.md" "Cyan"
Log "================================================================" "Cyan"

if (Test-Path $MEMORIA) {
    $stampFile = Get-Date -Format "yyyyMMdd_HHmmss"
    $backup = "$MEMORIA.bak_$stampFile"
    Copy-Item $MEMORIA $backup -Force
    Log "Backup criado: $backup" "Gray"
}

# Monta conteudo do MD em array de linhas (sem here-string)
$md = @()
$md += "# MEMORIA_PROJETO - DinDinVani&Nani"
$md += ""
$md += "> **App financeiro para casal** (Vani e Nani)"
$md += "> Gratuito, sem anuncios - Android + iOS + Web PWA"
$md += "> **Ultima atualizacao:** 01/06/2026"
$md += ""
$md += "---"
$md += ""
$md += "## Diretorio base"
$md += "``Z:\AppFinancas``"
$md += ""
$md += "> Desde 01/06/2026 o projeto vive em ``Z:\``."
$md += "> O caminho antigo ``C:\APP_Financas`` foi removido nesta data."
$md += ""
$md += "---"
$md += ""
$md += "## Filosofia Financeira (NUNCA VIOLAR)"
$md += ""
$md += "| Sigla | Nome | Regra |"
$md += "|-------|------|-------|"
$md += "| OD | Orcamento Defasado | Renda do mes M define orcamento de M+2 |"
$md += "| CF | Caixinha de Fatura | Cada compra no cartao reserva o valor na CF imediatamente |"
$md += "| CPI | Caixinha de Parcela Integral | Compra parcelada = valor TOTAL guardado no ato |"
$md += ""
$md += "**Regra de Ouro:** nunca somar a mesma despesa duas vezes."
$md += ""
$md += "---"
$md += ""
$md += "## Stack Tecnica"
$md += ""
$md += "- **Frontend:** Flutter 3.x + Dart"
$md += "- **State:** Riverpod 2.x"
$md += "- **Rotas:** go_router"
$md += "- **Graficos:** fl_chart"
$md += "- **Backend:** Supabase (PostgreSQL + RLS + Realtime)"
$md += "- **Notificacoes:** Firebase FCM (gratuito)"
$md += "- **Deploy:** Vercel (gratuito)"
$md += "- **CI/CD:** GitHub Actions (gratuito)"
$md += "- **Arquitetura:** Clean Architecture (core / data / domain / presentation)"
$md += ""
$md += "---"
$md += ""
$md += "## Supabase"
$md += ""
$md += "- **Projeto:** ``dindinvani``"
$md += "- **Project Ref:** ``xzbfdklyvgqlyowrlhfb``"
$md += "- **Regiao:** South America (Sao Paulo)"
$md += "- **URL:** ``https://xzbfdklyvgqlyowrlhfb.supabase.co``"
$md += "- **CLI instalada:** v2.101.0"
$md += ""
$md += "### Edge Functions deployadas (4/4 ACTIVE)"
$md += ""
$md += "| Funcao | Status | Versao | Deploy |"
$md += "|--------|--------|--------|--------|"
$md += "| generate_monthly_budget | ACTIVE | v1 | 01/06/2026 |"
$md += "| pay_cpi_installment | ACTIVE | v1 | 01/06/2026 |"
$md += "| pay_invoice_on_due_date | ACTIVE | v1 | 01/06/2026 |"
$md += "| recalculate_score | ACTIVE | v1 | 01/06/2026 |"
$md += ""
$md += "> Deploy realizado **sem Docker**, via flag ``--use-api``."
$md += ""
$md += "---"
$md += ""
$md += "## Banco de Dados (19 tabelas)"
$md += ""
$md += "families, users, accounts, credit_cards, invoices, invoice_reserves, transactions, recurring_transactions, piggy_banks, piggy_bank_contributions, piggy_bank_reservations, cpi_installment_payments, budgets, monthly_budgets, family_goals, categories, family_settings, audit_log, attachments"
$md += ""
$md += "**RLS obrigatorio em TODAS** - usuario so ve dados da propria familia."
$md += ""
$md += "---"
$md += ""
$md += "## PROGRESSO DOS 32 SCRIPTS"
$md += ""
$md += "### FASE 0 - Setup (7/7)"
$md += "- [x] 01 - check_deps"
$md += "- [x] 02 - install_scoop"
$md += "- [x] 03 - install_flutter"
$md += "- [x] 04 - install_node"
$md += "- [x] 05 - install_supabase"
$md += "- [x] 06 - install_git"
$md += "- [x] 07 - create_cursorrules"
$md += ""
$md += "### FASE 1 - Flutter + Supabase (4/4)"
$md += "- [x] 08 - create_flutter_project"
$md += "- [x] 09 - setup_pubspec"
$md += "- [x] 10 - init_supabase_local"
$md += "- [x] 11 - create_project_structure"
$md += ""
$md += "### FASE 2 - Banco de Dados (5/5)"
$md += "- [x] 12 - create_schema"
$md += "- [x] 13 - apply_rls"
$md += "- [x] 14 - create_triggers"
$md += "- [x] 15 - seed_categories"
$md += "- [x] 16 - create_edge_functions (deploy 01/06/2026 via --use-api)"
$md += ""
$md += "### FASE 3 - Flutter Core (0/4)"
$md += "- [ ] 17 - create_core_layer"
$md += "- [ ] 18 - create_data_layer"
$md += "- [ ] 19 - create_domain_layer"
$md += "- [ ] 20 - create_auth_feature"
$md += ""
$md += "### FASE 4 - Telas (0/7)"
$md += "- [ ] 21 - dashboard"
$md += "- [ ] 22 - transactions"
$md += "- [ ] 23 - piggy_banks"
$md += "- [ ] 24 - planning"
$md += "- [ ] 25 - credit_cards"
$md += "- [ ] 26 - reports"
$md += "- [ ] 27 - profile"
$md += ""
$md += "### FASE 5 - Deploy (0/5)"
$md += "- [ ] 28 - setup_firebase"
$md += "- [ ] 29 - setup_github_actions"
$md += "- [ ] 30 - build_android"
$md += "- [ ] 31 - build_web"
$md += "- [ ] 32 - deploy_vercel"
$md += ""
$md += "**Progresso total:** 16/32 (50%)"
$md += ""
$md += "---"
$md += ""
$md += "## Caminho base e Migracao"
$md += ""
$md += "- **Caminho atual:** ``Z:\AppFinancas``"
$md += "- **Caminho antigo:** ``C:\APP_Financas`` (removido em 01/06/2026)"
$md += "- **Backup descartado:** ``C:\APP_Financas_OLD_ate_script12`` (removido em 01/06/2026)"
$md += "- **Motivo:** liberar espaco em C: e isolar projeto em disco dedicado"
$md += ""
$md += "### Historico"
$md += "- **28/05/2026** - Projeto iniciado em C:\APP_Financas"
$md += "- **30/05/2026** - Scripts 01-15b executados"
$md += "- **01/06/2026** - Migracao para Z:\AppFinancas + deploy script 16 (sem Docker)"
$md += ""
$md += "---"
$md += ""
$md += "## Estrutura de pastas (Z:\AppFinancas)"
$md += ""
$md += "``````"
$md += "Z:\AppFinancas\"
$md += "|-- lib\                    <- codigo Flutter (Clean Architecture)"
$md += "|   |-- core\"
$md += "|   |-- data\"
$md += "|   |-- domain\"
$md += "|   \-- presentation\"
$md += "|-- supabase\"
$md += "|   |-- migrations\         <- schema, RLS, triggers, seeds"
$md += "|   |-- functions\          <- 4 Edge Functions"
$md += "|   \-- config.toml"
$md += "|-- scripts\setup\          <- os 32 scripts .ps1"
$md += "|-- logs\                   <- logs de cada execucao"
$md += "|-- android\ - ios\ - web\"
$md += "|-- pubspec.yaml"
$md += "\-- MEMORIA_PROJETO.md      <- este arquivo"
$md += "``````"
$md += ""
$md += "---"
$md += ""
$md += "## Dinamica de Trabalho"
$md += ""
$md += "1. **IA gera** o script .ps1 completo e autocontido"
$md += "2. **Cristiane roda** e cola o resultado no chat"
$md += "3. **IA confirma** e gera o proximo"
$md += "4. **Fim de sessao:** IA atualiza este arquivo marcando [x]"
$md += ""
$md += "### Comandos rapidos"
$md += "- ``PROXIMO`` -> gera o proximo script da sequencia"
$md += "- ``RESET`` -> rele o contexto do projeto do zero"
$md += ""
$md += "---"
$md += ""
$md += "## Proximo passo"
$md += ""
$md += "**Script 17 - create_core_layer**"
$md += "Criar lib/core/ com constants, extensions, errors, utils, theme e network."

# Salva UTF-8 sem BOM
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($MEMORIA, $md, $utf8NoBom)

Log "OK: MEMORIA_PROJETO.md reescrita" "Green"
Log "Tamanho: $((Get-Item $MEMORIA).Length) bytes" "Gray"
Log "Linhas: $($md.Count)" "Gray"

$check = Get-Content $MEMORIA -Raw -Encoding utf8
$ocrZ = [regex]::Matches($check, [regex]::Escape("Z:\AppFinancas")).Count
Log "Ocorrencias Z:\AppFinancas: $ocrZ" "Green"

Log "================================================================" "Cyan"
Log " MEMORIA atualizada com sucesso!" "Cyan"
Log "================================================================" "Cyan"
