$ErrorActionPreference = "Stop"
$BASE     = "Z:\AppFinancas"
$LIB      = "$BASE\lib"
$CORE     = "$LIB\core"
$LOG_DIR  = "$BASE\logs"
$LOG_FILE = "$LOG_DIR\17_create_core_layer.log"

if (-not (Test-Path $LOG_DIR)) { New-Item -ItemType Directory -Path $LOG_DIR -Force | Out-Null }

function Log {
    param([string]$msg, [string]$color = "White")
    $stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[$stamp] $msg"
    Write-Host $line -ForegroundColor $color
    Add-Content -Path $LOG_FILE -Value $line -Encoding utf8
}

function WriteDart {
    param([string]$path, [string[]]$content)
    $dir = Split-Path $path
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllLines($path, $content, $utf8NoBom)
    Log ("  + " + $path.Replace($BASE, "")) "Gray"
}

Log "================================================================" "Cyan"
Log " SCRIPT 17 - create_core_layer" "Cyan"
Log "================================================================" "Cyan"

Log "Criando estrutura lib/core/..." "Yellow"
$folders = @("constants","extensions","errors","utils","theme","network")
foreach ($f in $folders) {
    New-Item -ItemType Directory -Path "$CORE\$f" -Force | Out-Null
    Log "  pasta: lib/core/$f" "Gray"
}

# ============ app_colors.dart ============
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += ""
$c += "/// Paleta DinDinVani&Nani"
$c += "/// Vani = quente (ambar) | Nani = frio (azul)"
$c += "class AppColors {"
$c += "  AppColors._();"
$c += ""
$c += "  static const Color primary       = Color(0xFF6750A4);"
$c += "  static const Color primaryDark   = Color(0xFF4A3880);"
$c += "  static const Color primaryLight  = Color(0xFF9A82DB);"
$c += ""
$c += "  static const Color vani          = Color(0xFFE8865A);"
$c += "  static const Color vaniDark      = Color(0xFFB85F38);"
$c += "  static const Color vaniLight     = Color(0xFFFFB088);"
$c += ""
$c += "  static const Color nani          = Color(0xFF5A9BE8);"
$c += "  static const Color naniDark      = Color(0xFF3870B8);"
$c += "  static const Color naniLight     = Color(0xFF88BEFF);"
$c += ""
$c += "  static const Color success       = Color(0xFF2E7D32);"
$c += "  static const Color warning       = Color(0xFFF57C00);"
$c += "  static const Color danger        = Color(0xFFC62828);"
$c += "  static const Color info          = Color(0xFF0277BD);"
$c += ""
$c += "  static const Color scoreExcelente = Color(0xFF2E7D32);"
$c += "  static const Color scoreBom       = Color(0xFF9CCC65);"
$c += "  static const Color scoreAtencao   = Color(0xFFF57C00);"
$c += "  static const Color scoreCritico   = Color(0xFFC62828);"
$c += ""
$c += "  static const Color bgLight       = Color(0xFFFAF9FC);"
$c += "  static const Color bgDark        = Color(0xFF15131A);"
$c += "  static const Color surfaceLight  = Color(0xFFFFFFFF);"
$c += "  static const Color surfaceDark   = Color(0xFF1F1B24);"
$c += "}"
WriteDart "$CORE\constants\app_colors.dart" $c

# ============ app_strings.dart ============
$c = @()
$c += "class AppStrings {"
$c += "  AppStrings._();"
$c += ""
$c += "  static const String appName    = 'DinDinVani&Nani';"
$c += "  static const String appTagline = 'Financas a dois, sem brigas';"
$c += ""
$c += "  static const String odLabel  = 'Orcamento Defasado';"
$c += "  static const String cfLabel  = 'Caixinha de Fatura';"
$c += "  static const String cpiLabel = 'Caixinha de Parcela Integral';"
$c += "  static const String cpLabel  = 'Caixinha de Poupanca';"
$c += "  static const String cmLabel  = 'Caixinha de Meta';"
$c += "  static const String ceLabel  = 'Caixinha de Emergencia';"
$c += ""
$c += "  static const String errGeneric  = 'Algo deu errado. Tente novamente.';"
$c += "  static const String errNetwork  = 'Sem conexao com a internet.';"
$c += "  static const String errAuth     = 'Sessao expirada. Faca login novamente.';"
$c += "  static const String loading     = 'Carregando...';"
$c += "  static const String empty       = 'Nada por aqui ainda.';"
$c += "}"
WriteDart "$CORE\constants\app_strings.dart" $c

# ============ app_routes.dart ============
$c = @()
$c += "class AppRoutes {"
$c += "  AppRoutes._();"
$c += ""
$c += "  static const String splash       = '/';"
$c += "  static const String onboarding   = '/onboarding';"
$c += "  static const String login        = '/login';"
$c += "  static const String signup       = '/signup';"
$c += "  static const String dashboard    = '/dashboard';"
$c += "  static const String transactions = '/transactions';"
$c += "  static const String piggyBanks   = '/piggy-banks';"
$c += "  static const String planning     = '/planning';"
$c += "  static const String creditCards  = '/credit-cards';"
$c += "  static const String reports      = '/reports';"
$c += "  static const String profile      = '/profile';"
$c += "}"
WriteDart "$CORE\constants\app_routes.dart" $c

# ============ app_dimensions.dart ============
$c = @()
$c += "class AppDimensions {"
$c += "  AppDimensions._();"
$c += ""
$c += "  static const double paddingXs = 4.0;"
$c += "  static const double paddingSm = 8.0;"
$c += "  static const double paddingMd = 16.0;"
$c += "  static const double paddingLg = 24.0;"
$c += "  static const double paddingXl = 32.0;"
$c += ""
$c += "  static const double radiusSm = 8.0;"
$c += "  static const double radiusMd = 12.0;"
$c += "  static const double radiusLg = 20.0;"
$c += "  static const double radiusFull = 999.0;"
$c += ""
$c += "  static const double iconSm = 16.0;"
$c += "  static const double iconMd = 24.0;"
$c += "  static const double iconLg = 32.0;"
$c += ""
$c += "  static const double buttonHeight = 52.0;"
$c += "  static const double inputHeight  = 56.0;"
$c += "}"
WriteDart "$CORE\constants\app_dimensions.dart" $c

# ============ double_x.dart ============
$c = @()
$c += "import 'package:intl/intl.dart';"
$c += ""
$c += "extension DoubleX on double {"
$c += "  String toBRL({bool showSymbol = true}) {"
$c += "    final f = NumberFormat.currency("
$c += "      locale: 'pt_BR',"
$c += "      symbol: showSymbol ? 'R\$' : '',"
$c += "      decimalDigits: 2,"
$c += "    );"
$c += "    return f.format(this).trim();"
$c += "  }"
$c += ""
$c += "  String toBRNumber({int decimals = 2}) {"
$c += "    final f = NumberFormat.decimalPattern('pt_BR');"
$c += "    f.minimumFractionDigits = decimals;"
$c += "    f.maximumFractionDigits = decimals;"
$c += "    return f.format(this);"
$c += "  }"
$c += ""
$c += "  String toPercent({int decimals = 0}) {"
$c += "    final f = NumberFormat.percentPattern('pt_BR');"
$c += "    f.minimumFractionDigits = decimals;"
$c += "    f.maximumFractionDigits = decimals;"
$c += "    return f.format(this);"
$c += "  }"
$c += "}"
WriteDart "$CORE\extensions\double_x.dart" $c

# ============ datetime_x.dart ============
$c = @()
$c += "import 'package:intl/intl.dart';"
$c += ""
$c += "extension DateTimeX on DateTime {"
$c += "  String toBR() => DateFormat('dd/MM/yyyy', 'pt_BR').format(this);"
$c += ""
$c += "  String toBRTime() => DateFormat('dd/MM/yyyy HH:mm', 'pt_BR').format(this);"
$c += ""
$c += '  String toBRFull() => DateFormat("dd ''de'' MMMM ''de'' yyyy", "pt_BR").format(this);'
$c += ""
$c += "  String toMonthYear() => DateFormat('MMMM/yyyy', 'pt_BR').format(this);"
$c += ""
$c += "  String toShortMonth() => DateFormat('MMM/yy', 'pt_BR').format(this);"
$c += ""
$c += "  bool get isToday {"
$c += "    final n = DateTime.now();"
$c += "    return year == n.year && month == n.month && day == n.day;"
$c += "  }"
$c += ""
$c += "  DateTime get firstDayOfMonth => DateTime(year, month, 1);"
$c += "  DateTime get lastDayOfMonth  => DateTime(year, month + 1, 0);"
$c += ""
$c += "  DateTime addMonths(int n) => DateTime(year, month + n, day);"
$c += "}"
WriteDart "$CORE\extensions\datetime_x.dart" $c

# ============ string_x.dart ============
$c = @()
$c += "extension StringX on String {"
$c += "  String get capitalize {"
$c += "    if (isEmpty) return this;"
$c += "    return this[0].toUpperCase() + substring(1).toLowerCase();"
$c += "  }"
$c += ""
$c += "  String get titleCase => split(' ')"
$c += "      .map((w) => w.isEmpty ? w : w.capitalize)"
$c += "      .join(' ');"
$c += ""
$c += "  bool get isValidEmail =>"
$c += "      RegExp(r'^[\w.+-]+@[\w-]+\.[\w.-]+\$').hasMatch(this);"
$c += ""
$c += "  String get onlyDigits => replaceAll(RegExp(r'[^0-9]'), '');"
$c += ""
$c += "  double toBRDouble() {"
$c += "    final clean = replaceAll('R\$', '')"
$c += "        .replaceAll(' ', '')"
$c += "        .replaceAll('.', '')"
$c += "        .replaceAll(',', '.');"
$c += "    return double.tryParse(clean) ?? 0.0;"
$c += "  }"
$c += "}"
WriteDart "$CORE\extensions\string_x.dart" $c

Log "PARTE 1 OK - aguardando PARTE 2..." "Yellow"

# ============ failure.dart ============
$c = @()
$c += "abstract class Failure {"
$c += "  final String message;"
$c += "  final String? code;"
$c += "  const Failure(this.message, {this.code});"
$c += ""
$c += "  @override"
$c += "  String toString() => '\$runtimeType(\$code): \$message';"
$c += "}"
$c += ""
$c += "class NetworkFailure extends Failure {"
$c += "  const NetworkFailure([String msg = 'Sem conexao com a internet.'])"
$c += "      : super(msg, code: 'NETWORK');"
$c += "}"
$c += ""
$c += "class AuthFailure extends Failure {"
$c += "  const AuthFailure(super.message) : super(code: 'AUTH');"
$c += "}"
$c += ""
$c += "class DatabaseFailure extends Failure {"
$c += "  const DatabaseFailure(super.message) : super(code: 'DB');"
$c += "}"
$c += ""
$c += "class ValidationFailure extends Failure {"
$c += "  const ValidationFailure(super.message) : super(code: 'VALIDATION');"
$c += "}"
$c += ""
$c += "class BusinessRuleFailure extends Failure {"
$c += "  const BusinessRuleFailure(super.message) : super(code: 'BUSINESS');"
$c += "}"
$c += ""
$c += "class UnknownFailure extends Failure {"
$c += "  const UnknownFailure([String msg = 'Algo deu errado.'])"
$c += "      : super(msg, code: 'UNKNOWN');"
$c += "}"
WriteDart "$CORE\errors\failure.dart" $c

# ============ exceptions.dart ============
$c = @()
$c += "class ServerException implements Exception {"
$c += "  final String message;"
$c += "  final int? statusCode;"
$c += "  const ServerException(this.message, {this.statusCode});"
$c += "}"
$c += ""
$c += "class CacheException implements Exception {"
$c += "  final String message;"
$c += "  const CacheException(this.message);"
$c += "}"
$c += ""
$c += "class AuthException implements Exception {"
$c += "  final String message;"
$c += "  const AuthException(this.message);"
$c += "}"
$c += ""
$c += "class ValidationException implements Exception {"
$c += "  final String message;"
$c += "  const ValidationException(this.message);"
$c += "}"
WriteDart "$CORE\errors\exceptions.dart" $c

# ============ validators.dart ============
$c = @()
$c += "class Validators {"
$c += "  Validators._();"
$c += ""
$c += "  static String? required(String? v, {String campo = 'Campo'}) {"
$c += "    if (v == null || v.trim().isEmpty) return '\$campo obrigatorio';"
$c += "    return null;"
$c += "  }"
$c += ""
$c += "  static String? email(String? v) {"
$c += "    if (v == null || v.isEmpty) return 'E-mail obrigatorio';"
$c += "    final ok = RegExp(r'^[\w.+-]+@[\w-]+\.[\w.-]+\$').hasMatch(v);"
$c += "    return ok ? null : 'E-mail invalido';"
$c += "  }"
$c += ""
$c += "  static String? password(String? v) {"
$c += "    if (v == null || v.length < 6) return 'Senha deve ter no minimo 6 caracteres';"
$c += "    return null;"
$c += "  }"
$c += ""
$c += "  static String? positiveValue(String? v) {"
$c += "    if (v == null || v.isEmpty) return 'Valor obrigatorio';"
$c += "    final clean = v.replaceAll('.', '').replaceAll(',', '.');"
$c += "    final n = double.tryParse(clean);"
$c += "    if (n == null) return 'Valor invalido';"
$c += "    if (n <= 0) return 'Valor deve ser maior que zero';"
$c += "    return null;"
$c += "  }"
$c += "}"
WriteDart "$CORE\utils\validators.dart" $c

# ============ currency_input_formatter.dart ============
$c = @()
$c += "import 'package:flutter/services.dart';"
$c += "import 'package:intl/intl.dart';"
$c += ""
$c += "/// Formata input como R\$ enquanto o usuario digita."
$c += "class CurrencyInputFormatter extends TextInputFormatter {"
$c += "  final NumberFormat _f = NumberFormat.currency("
$c += "    locale: 'pt_BR',"
$c += "    symbol: 'R\$',"
$c += "    decimalDigits: 2,"
$c += "  );"
$c += ""
$c += "  @override"
$c += "  TextEditingValue formatEditUpdate(TextEditingValue oldV, TextEditingValue newV) {"
$c += "    if (newV.text.isEmpty) return newV.copyWith(text: '');"
$c += "    final digits = newV.text.replaceAll(RegExp(r'[^0-9]'), '');"
$c += "    if (digits.isEmpty) return const TextEditingValue(text: '');"
$c += "    final value = double.parse(digits) / 100;"
$c += "    final formatted = _f.format(value);"
$c += "    return TextEditingValue("
$c += "      text: formatted,"
$c += "      selection: TextSelection.collapsed(offset: formatted.length),"
$c += "    );"
$c += "  }"
$c += "}"
WriteDart "$CORE\utils\currency_input_formatter.dart" $c

# ============ app_theme.dart ============
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += "import '../constants/app_colors.dart';"
$c += "import '../constants/app_dimensions.dart';"
$c += ""
$c += "class AppTheme {"
$c += "  AppTheme._();"
$c += ""
$c += "  static ThemeData light() {"
$c += "    final scheme = ColorScheme.fromSeed("
$c += "      seedColor: AppColors.primary,"
$c += "      brightness: Brightness.light,"
$c += "    );"
$c += "    return _base(scheme, AppColors.bgLight, AppColors.surfaceLight);"
$c += "  }"
$c += ""
$c += "  static ThemeData dark() {"
$c += "    final scheme = ColorScheme.fromSeed("
$c += "      seedColor: AppColors.primary,"
$c += "      brightness: Brightness.dark,"
$c += "    );"
$c += "    return _base(scheme, AppColors.bgDark, AppColors.surfaceDark);"
$c += "  }"
$c += ""
$c += "  static ThemeData _base(ColorScheme scheme, Color bg, Color surface) {"
$c += "    return ThemeData("
$c += "      useMaterial3: true,"
$c += "      colorScheme: scheme,"
$c += "      scaffoldBackgroundColor: bg,"
$c += "      appBarTheme: AppBarTheme("
$c += "        backgroundColor: surface,"
$c += "        foregroundColor: scheme.onSurface,"
$c += "        elevation: 0,"
$c += "        centerTitle: true,"
$c += "      ),"
$c += "      cardTheme: CardThemeData("
$c += "        color: surface,"
$c += "        elevation: 1,"
$c += "        shape: RoundedRectangleBorder("
$c += "          borderRadius: BorderRadius.circular(AppDimensions.radiusMd),"
$c += "        ),"
$c += "      ),"
$c += "      elevatedButtonTheme: ElevatedButtonThemeData("
$c += "        style: ElevatedButton.styleFrom("
$c += "          minimumSize: const Size.fromHeight(AppDimensions.buttonHeight),"
$c += "          shape: RoundedRectangleBorder("
$c += "            borderRadius: BorderRadius.circular(AppDimensions.radiusMd),"
$c += "          ),"
$c += "        ),"
$c += "      ),"
$c += "      inputDecorationTheme: InputDecorationTheme("
$c += "        filled: true,"
$c += "        fillColor: surface,"
$c += "        border: OutlineInputBorder("
$c += "          borderRadius: BorderRadius.circular(AppDimensions.radiusMd),"
$c += "        ),"
$c += "      ),"
$c += "    );"
$c += "  }"
$c += "}"
WriteDart "$CORE\theme\app_theme.dart" $c

# ============ supabase_client.dart ============
$c = @()
$c += "import 'package:supabase_flutter/supabase_flutter.dart';"
$c += ""
$c += "/// Wrapper do cliente Supabase."
$c += "/// As chaves vem do .env via --dart-define."
$c += "class SupabaseService {"
$c += "  SupabaseService._();"
$c += ""
$c += "  static const String url = String.fromEnvironment("
$c += "    'SUPABASE_URL',"
$c += "    defaultValue: 'https://xzbfdklyvgqlyowrlhfb.supabase.co',"
$c += "  );"
$c += ""
$c += "  static const String anonKey = String.fromEnvironment("
$c += "    'SUPABASE_ANON_KEY',"
$c += "    defaultValue: '',"
$c += "  );"
$c += ""
$c += "  static Future<void> init() async {"
$c += "    await Supabase.initialize(url: url, anonKey: anonKey);"
$c += "  }"
$c += ""
$c += "  static SupabaseClient get client => Supabase.instance.client;"
$c += "  static User? get currentUser => client.auth.currentUser;"
$c += "  static bool get isAuthenticated => currentUser != null;"
$c += "}"
WriteDart "$CORE\network\supabase_client.dart" $c

# ============ api_constants.dart ============
$c = @()
$c += "class ApiConstants {"
$c += "  ApiConstants._();"
$c += ""
$c += "  // Edge Functions"
$c += "  static const String fnGenerateBudget   = 'generate_monthly_budget';"
$c += "  static const String fnPayCpiInstall    = 'pay_cpi_installment';"
$c += "  static const String fnPayInvoice       = 'pay_invoice_on_due_date';"
$c += "  static const String fnRecalculateScore = 'recalculate_score';"
$c += ""
$c += "  // Tabelas"
$c += "  static const String tFamilies     = 'families';"
$c += "  static const String tUsers        = 'users';"
$c += "  static const String tAccounts     = 'accounts';"
$c += "  static const String tCreditCards  = 'credit_cards';"
$c += "  static const String tInvoices     = 'invoices';"
$c += "  static const String tTransactions = 'transactions';"
$c += "  static const String tPiggyBanks   = 'piggy_banks';"
$c += "  static const String tBudgets      = 'budgets';"
$c += "  static const String tGoals        = 'family_goals';"
$c += "  static const String tCategories   = 'categories';"
$c += "}"
WriteDart "$CORE\network\api_constants.dart" $c

# ============ barrel core.dart ============
$c = @()
$c += "// Barrel file - facilita imports"
$c += "export 'constants/app_colors.dart';"
$c += "export 'constants/app_strings.dart';"
$c += "export 'constants/app_routes.dart';"
$c += "export 'constants/app_dimensions.dart';"
$c += "export 'extensions/double_x.dart';"
$c += "export 'extensions/datetime_x.dart';"
$c += "export 'extensions/string_x.dart';"
$c += "export 'errors/failure.dart';"
$c += "export 'errors/exceptions.dart';"
$c += "export 'utils/validators.dart';"
$c += "export 'utils/currency_input_formatter.dart';"
$c += "export 'theme/app_theme.dart';"
$c += "export 'network/supabase_client.dart';"
$c += "export 'network/api_constants.dart';"
WriteDart "$CORE\core.dart" $c

# ============ Resumo final ============
$totalFiles = (Get-ChildItem -Path $CORE -Recurse -File -Filter "*.dart").Count
Log "" "White"
Log "================================================================" "Cyan"
Log " RESUMO" "Cyan"
Log "================================================================" "Cyan"
Log "Arquivos .dart criados em lib/core: $totalFiles" "Green"
Log "Pastas: constants, extensions, errors, utils, theme, network" "Green"
Log "Barrel: lib/core/core.dart" "Green"
Log "================================================================" "Cyan"
Log " SCRIPT 17 - CONCLUIDO" "Cyan"
Log "================================================================" "Cyan"
