$ErrorActionPreference = "Stop"
$BASE     = "Z:\AppFinancas"
$LIB      = "$BASE\lib"
$DATA     = "$LIB\data"
$LOG_DIR  = "$BASE\logs"
$LOG_FILE = "$LOG_DIR\18_create_data_layer.log"

if (-not (Test-Path $LOG_DIR)) { New-Item -ItemType Directory -Path $LOG_DIR -Force | Out-Null }

function Log {
    param([string]$msg, [string]$color = "White")
    $stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[$stamp] $msg"
    Write-Host $line -ForegroundColor $color
    Add-Content -Path $LOG_FILE -Value $line -Encoding utf8
}

function WriteDart {
    param([string]$path, [string[]]$content)
    $dir = Split-Path $path
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllLines($path, $content, $utf8NoBom)
    Log ("  + " + $path.Replace($BASE, "")) "Gray"
}

Log "================================================================" "Cyan"
Log " SCRIPT 18 - create_data_layer" "Cyan"
Log "================================================================" "Cyan"

Log "Criando estrutura lib/data/..." "Yellow"
$folders = @("models","datasources","repositories")
foreach ($f in $folders) {
    New-Item -ItemType Directory -Path "$DATA\$f" -Force | Out-Null
    Log "  pasta: lib/data/$f" "Gray"
}

# ============ user_model.dart ============
$c = @()
$c += "class UserModel {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final String email;"
$c += "  final String name;"
$c += "  final String role; // 'vani' ou 'nani'"
$c += "  final String? avatarUrl;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const UserModel({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.email,"
$c += "    required this.name,"
$c += "    required this.role,"
$c += "    this.avatarUrl,"
$c += "    required this.createdAt,"
$c += "  });"
$c += ""
$c += "  factory UserModel.fromJson(Map<String, dynamic> j) => UserModel("
$c += "        id: j['id'] as String,"
$c += "        familyId: j['family_id'] as String,"
$c += "        email: j['email'] as String,"
$c += "        name: j['name'] as String,"
$c += "        role: j['role'] as String,"
$c += "        avatarUrl: j['avatar_url'] as String?,"
$c += "        createdAt: DateTime.parse(j['created_at'] as String),"
$c += "      );"
$c += ""
$c += "  Map<String, dynamic> toJson() => {"
$c += "        'id': id,"
$c += "        'family_id': familyId,"
$c += "        'email': email,"
$c += "        'name': name,"
$c += "        'role': role,"
$c += "        'avatar_url': avatarUrl,"
$c += "        'created_at': createdAt.toIso8601String(),"
$c += "      };"
$c += "}"
WriteDart "$DATA\models\user_model.dart" $c

# ============ family_model.dart ============
$c = @()
$c += "class FamilyModel {"
$c += "  final String id;"
$c += "  final String name;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const FamilyModel({"
$c += "    required this.id,"
$c += "    required this.name,"
$c += "    required this.createdAt,"
$c += "  });"
$c += ""
$c += "  factory FamilyModel.fromJson(Map<String, dynamic> j) => FamilyModel("
$c += "        id: j['id'] as String,"
$c += "        name: j['name'] as String,"
$c += "        createdAt: DateTime.parse(j['created_at'] as String),"
$c += "      );"
$c += ""
$c += "  Map<String, dynamic> toJson() => {"
$c += "        'id': id,"
$c += "        'name': name,"
$c += "        'created_at': createdAt.toIso8601String(),"
$c += "      };"
$c += "}"
WriteDart "$DATA\models\family_model.dart" $c

# ============ account_model.dart ============
$c = @()
$c += "class AccountModel {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final String name;"
$c += "  final String type; // checking, savings, wallet"
$c += "  final double balance;"
$c += "  final String? bankName;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const AccountModel({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.name,"
$c += "    required this.type,"
$c += "    required this.balance,"
$c += "    this.bankName,"
$c += "    required this.createdAt,"
$c += "  });"
$c += ""
$c += "  factory AccountModel.fromJson(Map<String, dynamic> j) => AccountModel("
$c += "        id: j['id'] as String,"
$c += "        familyId: j['family_id'] as String,"
$c += "        name: j['name'] as String,"
$c += "        type: j['type'] as String,"
$c += "        balance: (j['balance'] as num).toDouble(),"
$c += "        bankName: j['bank_name'] as String?,"
$c += "        createdAt: DateTime.parse(j['created_at'] as String),"
$c += "      );"
$c += ""
$c += "  Map<String, dynamic> toJson() => {"
$c += "        'id': id,"
$c += "        'family_id': familyId,"
$c += "        'name': name,"
$c += "        'type': type,"
$c += "        'balance': balance,"
$c += "        'bank_name': bankName,"
$c += "      };"
$c += "}"
WriteDart "$DATA\models\account_model.dart" $c

# ============ transaction_model.dart ============
$c = @()
$c += "class TransactionModel {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final String userId;"
$c += "  final String type; // income, expense, transfer"
$c += "  final double amount;"
$c += "  final String description;"
$c += "  final String? categoryId;"
$c += "  final String? accountId;"
$c += "  final String? creditCardId;"
$c += "  final String? piggyBankId;"
$c += "  final int? installmentNumber;"
$c += "  final int? totalInstallments;"
$c += "  final DateTime date;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const TransactionModel({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.userId,"
$c += "    required this.type,"
$c += "    required this.amount,"
$c += "    required this.description,"
$c += "    this.categoryId,"
$c += "    this.accountId,"
$c += "    this.creditCardId,"
$c += "    this.piggyBankId,"
$c += "    this.installmentNumber,"
$c += "    this.totalInstallments,"
$c += "    required this.date,"
$c += "    required this.createdAt,"
$c += "  });"
$c += ""
$c += "  factory TransactionModel.fromJson(Map<String, dynamic> j) => TransactionModel("
$c += "        id: j['id'] as String,"
$c += "        familyId: j['family_id'] as String,"
$c += "        userId: j['user_id'] as String,"
$c += "        type: j['type'] as String,"
$c += "        amount: (j['amount'] as num).toDouble(),"
$c += "        description: j['description'] as String,"
$c += "        categoryId: j['category_id'] as String?,"
$c += "        accountId: j['account_id'] as String?,"
$c += "        creditCardId: j['credit_card_id'] as String?,"
$c += "        piggyBankId: j['piggy_bank_id'] as String?,"
$c += "        installmentNumber: j['installment_number'] as int?,"
$c += "        totalInstallments: j['total_installments'] as int?,"
$c += "        date: DateTime.parse(j['date'] as String),"
$c += "        createdAt: DateTime.parse(j['created_at'] as String),"
$c += "      );"
$c += ""
$c += "  Map<String, dynamic> toJson() => {"
$c += "        'family_id': familyId,"
$c += "        'user_id': userId,"
$c += "        'type': type,"
$c += "        'amount': amount,"
$c += "        'description': description,"
$c += "        'category_id': categoryId,"
$c += "        'account_id': accountId,"
$c += "        'credit_card_id': creditCardId,"
$c += "        'piggy_bank_id': piggyBankId,"
$c += "        'installment_number': installmentNumber,"
$c += "        'total_installments': totalInstallments,"
$c += "        'date': date.toIso8601String(),"
$c += "      };"
$c += "}"
WriteDart "$DATA\models\transaction_model.dart" $c

# ============ piggy_bank_model.dart ============
$c = @()
$c += "class PiggyBankModel {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final String name;"
$c += "  final String type; // CF, CPI, CP, CM, CE"
$c += "  final double currentAmount;"
$c += "  final double? targetAmount;"
$c += "  final String? creditCardId; // se CF"
$c += "  final String? goalId; // se CM"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const PiggyBankModel({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.name,"
$c += "    required this.type,"
$c += "    required this.currentAmount,"
$c += "    this.targetAmount,"
$c += "    this.creditCardId,"
$c += "    this.goalId,"
$c += "    required this.createdAt,"
$c += "  });"
$c += ""
$c += "  factory PiggyBankModel.fromJson(Map<String, dynamic> j) => PiggyBankModel("
$c += "        id: j['id'] as String,"
$c += "        familyId: j['family_id'] as String,"
$c += "        name: j['name'] as String,"
$c += "        type: j['type'] as String,"
$c += "        currentAmount: (j['current_amount'] as num).toDouble(),"
$c += "        targetAmount: (j['target_amount'] as num?)?.toDouble(),"
$c += "        creditCardId: j['credit_card_id'] as String?,"
$c += "        goalId: j['goal_id'] as String?,"
$c += "        createdAt: DateTime.parse(j['created_at'] as String),"
$c += "      );"
$c += ""
$c += "  Map<String, dynamic> toJson() => {"
$c += "        'family_id': familyId,"
$c += "        'name': name,"
$c += "        'type': type,"
$c += "        'current_amount': currentAmount,"
$c += "        'target_amount': targetAmount,"
$c += "        'credit_card_id': creditCardId,"
$c += "        'goal_id': goalId,"
$c += "      };"
$c += "}"
WriteDart "$DATA\models\piggy_bank_model.dart" $c

# ============ credit_card_model.dart ============
$c = @()
$c += "class CreditCardModel {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final String name;"
$c += "  final double creditLimit;"
$c += "  final int closingDay;"
$c += "  final int dueDay;"
$c += "  final String? brand;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const CreditCardModel({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.name,"
$c += "    required this.creditLimit,"
$c += "    required this.closingDay,"
$c += "    required this.dueDay,"
$c += "    this.brand,"
$c += "    required this.createdAt,"
$c += "  });"
$c += ""
$c += "  factory CreditCardModel.fromJson(Map<String, dynamic> j) => CreditCardModel("
$c += "        id: j['id'] as String,"
$c += "        familyId: j['family_id'] as String,"
$c += "        name: j['name'] as String,"
$c += "        creditLimit: (j['credit_limit'] as num).toDouble(),"
$c += "        closingDay: j['closing_day'] as int,"
$c += "        dueDay: j['due_day'] as int,"
$c += "        brand: j['brand'] as String?,"
$c += "        createdAt: DateTime.parse(j['created_at'] as String),"
$c += "      );"
$c += ""
$c += "  Map<String, dynamic> toJson() => {"
$c += "        'family_id': familyId,"
$c += "        'name': name,"
$c += "        'credit_limit': creditLimit,"
$c += "        'closing_day': closingDay,"
$c += "        'due_day': dueDay,"
$c += "        'brand': brand,"
$c += "      };"
$c += "}"
WriteDart "$DATA\models\credit_card_model.dart" $c

# ============ invoice_model.dart ============
$c = @()
$c += "class InvoiceModel {"
$c += "  final String id;"
$c += "  final String creditCardId;"
$c += "  final String familyId;"
$c += "  final int referenceMonth;"
$c += "  final int referenceYear;"
$c += "  final double totalAmount;"
$c += "  final double reservedAmount;"
$c += "  final DateTime closingDate;"
$c += "  final DateTime dueDate;"
$c += "  final String status; // open, closed, paid"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const InvoiceModel({"
$c += "    required this.id,"
$c += "    required this.creditCardId,"
$c += "    required this.familyId,"
$c += "    required this.referenceMonth,"
$c += "    required this.referenceYear,"
$c += "    required this.totalAmount,"
$c += "    required this.reservedAmount,"
$c += "    required this.closingDate,"
$c += "    required this.dueDate,"
$c += "    required this.status,"
$c += "    required this.createdAt,"
$c += "  });"
$c += ""
$c += "  double get coverage => totalAmount > 0 ? reservedAmount / totalAmount : 1.0;"
$c += ""
$c += "  factory InvoiceModel.fromJson(Map<String, dynamic> j) => InvoiceModel("
$c += "        id: j['id'] as String,"
$c += "        creditCardId: j['credit_card_id'] as String,"
$c += "        familyId: j['family_id'] as String,"
$c += "        referenceMonth: j['reference_month'] as int,"
$c += "        referenceYear: j['reference_year'] as int,"
$c += "        totalAmount: (j['total_amount'] as num).toDouble(),"
$c += "        reservedAmount: (j['reserved_amount'] as num).toDouble(),"
$c += "        closingDate: DateTime.parse(j['closing_date'] as String),"
$c += "        dueDate: DateTime.parse(j['due_date'] as String),"
$c += "        status: j['status'] as String,"
$c += "        createdAt: DateTime.parse(j['created_at'] as String),"
$c += "      );"
$c += "}"
WriteDart "$DATA\models\invoice_model.dart" $c

# ============ category_model.dart ============
$c = @()
$c += "class CategoryModel {"
$c += "  final String id;"
$c += "  final String? familyId;"
$c += "  final String name;"
$c += "  final String type; // income, expense"
$c += "  final String icon;"
$c += "  final String color;"
$c += "  final bool isDefault;"
$c += ""
$c += "  const CategoryModel({"
$c += "    required this.id,"
$c += "    this.familyId,"
$c += "    required this.name,"
$c += "    required this.type,"
$c += "    required this.icon,"
$c += "    required this.color,"
$c += "    required this.isDefault,"
$c += "  });"
$c += ""
$c += "  factory CategoryModel.fromJson(Map<String, dynamic> j) => CategoryModel("
$c += "        id: j['id'] as String,"
$c += "        familyId: j['family_id'] as String?,"
$c += "        name: j['name'] as String,"
$c += "        type: j['type'] as String,"
$c += "        icon: j['icon'] as String,"
$c += "        color: j['color'] as String,"
$c += "        isDefault: j['is_default'] as bool? ?? false,"
$c += "      );"
$c += ""
$c += "  Map<String, dynamic> toJson() => {"
$c += "        'family_id': familyId,"
$c += "        'name': name,"
$c += "        'type': type,"
$c += "        'icon': icon,"
$c += "        'color': color,"
$c += "        'is_default': isDefault,"
$c += "      };"
$c += "}"
WriteDart "$DATA\models\category_model.dart" $c

# ============ budget_model.dart ============
$c = @()
$c += "class BudgetModel {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final int referenceMonth;"
$c += "  final int referenceYear;"
$c += "  final double totalIncome; // renda do mes M (vira orcamento M+2)"
$c += "  final double needsAmount; // 50%"
$c += "  final double wantsAmount; // 30%"
$c += "  final double savingsAmount; // 20%"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const BudgetModel({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.referenceMonth,"
$c += "    required this.referenceYear,"
$c += "    required this.totalIncome,"
$c += "    required this.needsAmount,"
$c += "    required this.wantsAmount,"
$c += "    required this.savingsAmount,"
$c += "    required this.createdAt,"
$c += "  });"
$c += ""
$c += "  factory BudgetModel.fromJson(Map<String, dynamic> j) => BudgetModel("
$c += "        id: j['id'] as String,"
$c += "        familyId: j['family_id'] as String,"
$c += "        referenceMonth: j['reference_month'] as int,"
$c += "        referenceYear: j['reference_year'] as int,"
$c += "        totalIncome: (j['total_income'] as num).toDouble(),"
$c += "        needsAmount: (j['needs_amount'] as num).toDouble(),"
$c += "        wantsAmount: (j['wants_amount'] as num).toDouble(),"
$c += "        savingsAmount: (j['savings_amount'] as num).toDouble(),"
$c += "        createdAt: DateTime.parse(j['created_at'] as String),"
$c += "      );"
$c += "}"
WriteDart "$DATA\models\budget_model.dart" $c

# ============ goal_model.dart ============
$c = @()
$c += "class GoalModel {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final String name;"
$c += "  final double targetAmount;"
$c += "  final double currentAmount;"
$c += "  final DateTime? targetDate;"
$c += "  final String? icon;"
$c += "  final String status; // active, completed, paused"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const GoalModel({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.name,"
$c += "    required this.targetAmount,"
$c += "    required this.currentAmount,"
$c += "    this.targetDate,"
$c += "    this.icon,"
$c += "    required this.status,"
$c += "    required this.createdAt,"
$c += "  });"
$c += ""
$c += "  double get progress => targetAmount > 0 ? currentAmount / targetAmount : 0.0;"
$c += ""
$c += "  factory GoalModel.fromJson(Map<String, dynamic> j) => GoalModel("
$c += "        id: j['id'] as String,"
$c += "        familyId: j['family_id'] as String,"
$c += "        name: j['name'] as String,"
$c += "        targetAmount: (j['target_amount'] as num).toDouble(),"
$c += "        currentAmount: (j['current_amount'] as num).toDouble(),"
$c += "        targetDate: j['target_date'] != null ? DateTime.parse(j['target_date'] as String) : null,"
$c += "        icon: j['icon'] as String?,"
$c += "        status: j['status'] as String,"
$c += "        createdAt: DateTime.parse(j['created_at'] as String),"
$c += "      );"
$c += "}"
WriteDart "$DATA\models\goal_model.dart" $c

Log "PARTE 1 OK - 10 models criados. Aguardando PARTE 2..." "Yellow"

# ============ auth_remote_datasource.dart ============
$c = @()
$c += "import 'package:supabase_flutter/supabase_flutter.dart';"
$c += "import '../../core/network/supabase_client.dart';"
$c += "import '../../core/errors/exceptions.dart';"
$c += "import '../models/user_model.dart';"
$c += ""
$c += "class AuthRemoteDataSource {"
$c += "  final SupabaseClient _client = SupabaseService.client;"
$c += ""
$c += "  Future<AuthResponse> signIn(String email, String password) async {"
$c += "    try {"
$c += "      return await _client.auth.signInWithPassword(email: email, password: password);"
$c += "    } on AuthException catch (e) {"
$c += "      throw AuthException(e.message);"
$c += "    } catch (e) {"
$c += "      throw ServerException(e.toString());"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<AuthResponse> signUp({"
$c += "    required String email,"
$c += "    required String password,"
$c += "    required String name,"
$c += "  }) async {"
$c += "    try {"
$c += "      return await _client.auth.signUp("
$c += "        email: email,"
$c += "        password: password,"
$c += "        data: {'name': name},"
$c += "      );"
$c += "    } on AuthException catch (e) {"
$c += "      throw AuthException(e.message);"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<void> signOut() async {"
$c += "    await _client.auth.signOut();"
$c += "  }"
$c += ""
$c += "  Future<UserModel?> getCurrentUserProfile() async {"
$c += "    final user = _client.auth.currentUser;"
$c += "    if (user == null) return null;"
$c += "    final data = await _client.from('users').select().eq('id', user.id).maybeSingle();"
$c += "    if (data == null) return null;"
$c += "    return UserModel.fromJson(data);"
$c += "  }"
$c += ""
$c += "  Stream<AuthState> get authStateChanges => _client.auth.onAuthStateChange;"
$c += "}"
WriteDart "$DATA\datasources\auth_remote_datasource.dart" $c

# ============ transactions_remote_datasource.dart ============
$c = @()
$c += "import 'package:supabase_flutter/supabase_flutter.dart';"
$c += "import '../../core/network/supabase_client.dart';"
$c += "import '../../core/errors/exceptions.dart';"
$c += "import '../models/transaction_model.dart';"
$c += ""
$c += "class TransactionsRemoteDataSource {"
$c += "  final SupabaseClient _c = SupabaseService.client;"
$c += ""
$c += "  Future<List<TransactionModel>> listByMonth({"
$c += "    required String familyId,"
$c += "    required int month,"
$c += "    required int year,"
$c += "  }) async {"
$c += "    try {"
$c += "      final start = DateTime(year, month, 1).toIso8601String();"
$c += "      final end = DateTime(year, month + 1, 1).toIso8601String();"
$c += "      final data = await _c"
$c += "          .from('transactions')"
$c += "          .select()"
$c += "          .eq('family_id', familyId)"
$c += "          .gte('date', start)"
$c += "          .lt('date', end)"
$c += "          .order('date', ascending: false);"
$c += "      return (data as List).map((e) => TransactionModel.fromJson(e)).toList();"
$c += "    } catch (e) {"
$c += "      throw ServerException(e.toString());"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<TransactionModel> insert(TransactionModel t) async {"
$c += "    try {"
$c += "      final data = await _c.from('transactions').insert(t.toJson()).select().single();"
$c += "      return TransactionModel.fromJson(data);"
$c += "    } catch (e) {"
$c += "      throw ServerException(e.toString());"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<void> delete(String id) async {"
$c += "    await _c.from('transactions').delete().eq('id', id);"
$c += "  }"
$c += ""
$c += "  Future<TransactionModel> update(String id, Map<String, dynamic> fields) async {"
$c += "    final data = await _c.from('transactions').update(fields).eq('id', id).select().single();"
$c += "    return TransactionModel.fromJson(data);"
$c += "  }"
$c += ""
$c += "  Stream<List<TransactionModel>> watchByFamily(String familyId) {"
$c += "    return _c"
$c += "        .from('transactions')"
$c += "        .stream(primaryKey: ['id'])"
$c += "        .eq('family_id', familyId)"
$c += "        .order('date', ascending: false)"
$c += "        .map((rows) => rows.map((e) => TransactionModel.fromJson(e)).toList());"
$c += "  }"
$c += "}"
WriteDart "$DATA\datasources\transactions_remote_datasource.dart" $c

# ============ piggy_banks_remote_datasource.dart ============
$c = @()
$c += "import 'package:supabase_flutter/supabase_flutter.dart';"
$c += "import '../../core/network/supabase_client.dart';"
$c += "import '../../core/errors/exceptions.dart';"
$c += "import '../models/piggy_bank_model.dart';"
$c += ""
$c += "class PiggyBanksRemoteDataSource {"
$c += "  final SupabaseClient _c = SupabaseService.client;"
$c += ""
$c += "  Future<List<PiggyBankModel>> list(String familyId) async {"
$c += "    try {"
$c += "      final data = await _c"
$c += "          .from('piggy_banks')"
$c += "          .select()"
$c += "          .eq('family_id', familyId)"
$c += "          .order('type')"
$c += "          .order('name');"
$c += "      return (data as List).map((e) => PiggyBankModel.fromJson(e)).toList();"
$c += "    } catch (e) {"
$c += "      throw ServerException(e.toString());"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<PiggyBankModel> insert(PiggyBankModel p) async {"
$c += "    final data = await _c.from('piggy_banks').insert(p.toJson()).select().single();"
$c += "    return PiggyBankModel.fromJson(data);"
$c += "  }"
$c += ""
$c += "  Future<void> contribute({"
$c += "    required String piggyBankId,"
$c += "    required double amount,"
$c += "    required String userId,"
$c += "  }) async {"
$c += "    await _c.from('piggy_bank_contributions').insert({"
$c += "      'piggy_bank_id': piggyBankId,"
$c += "      'amount': amount,"
$c += "      'user_id': userId,"
$c += "    });"
$c += "  }"
$c += ""
$c += "  Stream<List<PiggyBankModel>> watch(String familyId) {"
$c += "    return _c"
$c += "        .from('piggy_banks')"
$c += "        .stream(primaryKey: ['id'])"
$c += "        .eq('family_id', familyId)"
$c += "        .map((rows) => rows.map((e) => PiggyBankModel.fromJson(e)).toList());"
$c += "  }"
$c += "}"
WriteDart "$DATA\datasources\piggy_banks_remote_datasource.dart" $c

# ============ credit_cards_remote_datasource.dart ============
$c = @()
$c += "import 'package:supabase_flutter/supabase_flutter.dart';"
$c += "import '../../core/network/supabase_client.dart';"
$c += "import '../../core/errors/exceptions.dart';"
$c += "import '../models/credit_card_model.dart';"
$c += "import '../models/invoice_model.dart';"
$c += ""
$c += "class CreditCardsRemoteDataSource {"
$c += "  final SupabaseClient _c = SupabaseService.client;"
$c += ""
$c += "  Future<List<CreditCardModel>> list(String familyId) async {"
$c += "    try {"
$c += "      final data = await _c.from('credit_cards').select().eq('family_id', familyId);"
$c += "      return (data as List).map((e) => CreditCardModel.fromJson(e)).toList();"
$c += "    } catch (e) {"
$c += "      throw ServerException(e.toString());"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<CreditCardModel> insert(CreditCardModel card) async {"
$c += "    final data = await _c.from('credit_cards').insert(card.toJson()).select().single();"
$c += "    return CreditCardModel.fromJson(data);"
$c += "  }"
$c += ""
$c += "  Future<List<InvoiceModel>> listInvoices(String creditCardId) async {"
$c += "    final data = await _c"
$c += "        .from('invoices')"
$c += "        .select()"
$c += "        .eq('credit_card_id', creditCardId)"
$c += "        .order('reference_year', ascending: false)"
$c += "        .order('reference_month', ascending: false);"
$c += "    return (data as List).map((e) => InvoiceModel.fromJson(e)).toList();"
$c += "  }"
$c += ""
$c += "  Future<InvoiceModel?> getCurrentInvoice(String creditCardId) async {"
$c += "    final now = DateTime.now();"
$c += "    final data = await _c"
$c += "        .from('invoices')"
$c += "        .select()"
$c += "        .eq('credit_card_id', creditCardId)"
$c += "        .eq('reference_month', now.month)"
$c += "        .eq('reference_year', now.year)"
$c += "        .maybeSingle();"
$c += "    if (data == null) return null;"
$c += "    return InvoiceModel.fromJson(data);"
$c += "  }"
$c += "}"
WriteDart "$DATA\datasources\credit_cards_remote_datasource.dart" $c

# ============ categories_remote_datasource.dart ============
$c = @()
$c += "import 'package:supabase_flutter/supabase_flutter.dart';"
$c += "import '../../core/network/supabase_client.dart';"
$c += "import '../models/category_model.dart';"
$c += ""
$c += "class CategoriesRemoteDataSource {"
$c += "  final SupabaseClient _c = SupabaseService.client;"
$c += ""
$c += "  Future<List<CategoryModel>> list(String familyId) async {"
$c += "    final data = await _c"
$c += "        .from('categories')"
$c += "        .select()"
$c += "        .or('family_id.eq.\$familyId,is_default.eq.true')"
$c += "        .order('type')"
$c += "        .order('name');"
$c += "    return (data as List).map((e) => CategoryModel.fromJson(e)).toList();"
$c += "  }"
$c += "}"
WriteDart "$DATA\datasources\categories_remote_datasource.dart" $c

# ============ budgets_remote_datasource.dart ============
$c = @()
$c += "import 'package:supabase_flutter/supabase_flutter.dart';"
$c += "import '../../core/network/supabase_client.dart';"
$c += "import '../models/budget_model.dart';"
$c += ""
$c += "class BudgetsRemoteDataSource {"
$c += "  final SupabaseClient _c = SupabaseService.client;"
$c += ""
$c += "  Future<BudgetModel?> getCurrent(String familyId) async {"
$c += "    final now = DateTime.now();"
$c += "    final data = await _c"
$c += "        .from('monthly_budgets')"
$c += "        .select()"
$c += "        .eq('family_id', familyId)"
$c += "        .eq('reference_month', now.month)"
$c += "        .eq('reference_year', now.year)"
$c += "        .maybeSingle();"
$c += "    if (data == null) return null;"
$c += "    return BudgetModel.fromJson(data);"
$c += "  }"
$c += ""
$c += "  Future<List<BudgetModel>> listHistory(String familyId, {int limit = 12}) async {"
$c += "    final data = await _c"
$c += "        .from('monthly_budgets')"
$c += "        .select()"
$c += "        .eq('family_id', familyId)"
$c += "        .order('reference_year', ascending: false)"
$c += "        .order('reference_month', ascending: false)"
$c += "        .limit(limit);"
$c += "    return (data as List).map((e) => BudgetModel.fromJson(e)).toList();"
$c += "  }"
$c += "}"
WriteDart "$DATA\datasources\budgets_remote_datasource.dart" $c

# ============ goals_remote_datasource.dart ============
$c = @()
$c += "import 'package:supabase_flutter/supabase_flutter.dart';"
$c += "import '../../core/network/supabase_client.dart';"
$c += "import '../models/goal_model.dart';"
$c += ""
$c += "class GoalsRemoteDataSource {"
$c += "  final SupabaseClient _c = SupabaseService.client;"
$c += ""
$c += "  Future<List<GoalModel>> list(String familyId) async {"
$c += "    final data = await _c"
$c += "        .from('family_goals')"
$c += "        .select()"
$c += "        .eq('family_id', familyId)"
$c += "        .order('created_at', ascending: false);"
$c += "    return (data as List).map((e) => GoalModel.fromJson(e)).toList();"
$c += "  }"
$c += ""
$c += "  Future<GoalModel> insert(Map<String, dynamic> data) async {"
$c += "    final res = await _c.from('family_goals').insert(data).select().single();"
$c += "    return GoalModel.fromJson(res);"
$c += "  }"
$c += "}"
WriteDart "$DATA\datasources\goals_remote_datasource.dart" $c

Log "PARTE 2 OK - 7 datasources criados. Aguardando PARTE 3..." "Yellow"

# ============ auth_repository_impl.dart ============
$c = @()
$c += "import '../datasources/auth_remote_datasource.dart';"
$c += "import '../models/user_model.dart';"
$c += "import '../../core/errors/exceptions.dart';"
$c += "import '../../core/errors/failure.dart';"
$c += ""
$c += "class AuthRepositoryImpl {"
$c += "  final AuthRemoteDataSource remote;"
$c += "  AuthRepositoryImpl(this.remote);"
$c += ""
$c += "  Future<UserModel?> signIn(String email, String password) async {"
$c += "    try {"
$c += "      await remote.signIn(email, password);"
$c += "      return await remote.getCurrentUserProfile();"
$c += "    } on AuthException catch (e) {"
$c += "      throw AuthFailure(e.message);"
$c += "    } on ServerException catch (e) {"
$c += "      throw DatabaseFailure(e.message);"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<void> signUp({"
$c += "    required String email,"
$c += "    required String password,"
$c += "    required String name,"
$c += "  }) async {"
$c += "    try {"
$c += "      await remote.signUp(email: email, password: password, name: name);"
$c += "    } on AuthException catch (e) {"
$c += "      throw AuthFailure(e.message);"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<void> signOut() => remote.signOut();"
$c += ""
$c += "  Future<UserModel?> currentUserProfile() => remote.getCurrentUserProfile();"
$c += "}"
WriteDart "$DATA\repositories\auth_repository_impl.dart" $c

# ============ transactions_repository_impl.dart ============
$c = @()
$c += "import '../datasources/transactions_remote_datasource.dart';"
$c += "import '../models/transaction_model.dart';"
$c += "import '../../core/errors/exceptions.dart';"
$c += "import '../../core/errors/failure.dart';"
$c += ""
$c += "class TransactionsRepositoryImpl {"
$c += "  final TransactionsRemoteDataSource remote;"
$c += "  TransactionsRepositoryImpl(this.remote);"
$c += ""
$c += "  Future<List<TransactionModel>> getByMonth({"
$c += "    required String familyId,"
$c += "    required int month,"
$c += "    required int year,"
$c += "  }) async {"
$c += "    try {"
$c += "      return await remote.listByMonth(familyId: familyId, month: month, year: year);"
$c += "    } on ServerException catch (e) {"
$c += "      throw DatabaseFailure(e.message);"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<TransactionModel> create(TransactionModel t) async {"
$c += "    if (t.amount <= 0) {"
$c += "      throw const ValidationFailure('Valor deve ser maior que zero');"
$c += "    }"
$c += "    try {"
$c += "      return await remote.insert(t);"
$c += "    } on ServerException catch (e) {"
$c += "      throw DatabaseFailure(e.message);"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<void> delete(String id) => remote.delete(id);"
$c += ""
$c += "  Future<TransactionModel> update(String id, Map<String, dynamic> fields) =>"
$c += "      remote.update(id, fields);"
$c += ""
$c += "  Stream<List<TransactionModel>> watch(String familyId) => remote.watchByFamily(familyId);"
$c += "}"
WriteDart "$DATA\repositories\transactions_repository_impl.dart" $c

# ============ piggy_banks_repository_impl.dart ============
$c = @()
$c += "import '../datasources/piggy_banks_remote_datasource.dart';"
$c += "import '../models/piggy_bank_model.dart';"
$c += "import '../../core/errors/failure.dart';"
$c += ""
$c += "class PiggyBanksRepositoryImpl {"
$c += "  final PiggyBanksRemoteDataSource remote;"
$c += "  PiggyBanksRepositoryImpl(this.remote);"
$c += ""
$c += "  Future<List<PiggyBankModel>> list(String familyId) => remote.list(familyId);"
$c += ""
$c += "  Future<PiggyBankModel> create(PiggyBankModel p) async {"
$c += "    const validTypes = ['CF', 'CPI', 'CP', 'CM', 'CE'];"
$c += "    if (!validTypes.contains(p.type)) {"
$c += "      throw ValidationFailure('Tipo de caixinha invalido: \${p.type}');"
$c += "    }"
$c += "    if (p.type == 'CF' && p.creditCardId == null) {"
$c += "      throw const BusinessRuleFailure('Caixinha de Fatura precisa de cartao vinculado');"
$c += "    }"
$c += "    return remote.insert(p);"
$c += "  }"
$c += ""
$c += "  Future<void> contribute({"
$c += "    required String piggyBankId,"
$c += "    required double amount,"
$c += "    required String userId,"
$c += "  }) async {"
$c += "    if (amount <= 0) {"
$c += "      throw const ValidationFailure('Valor da contribuicao deve ser maior que zero');"
$c += "    }"
$c += "    return remote.contribute(piggyBankId: piggyBankId, amount: amount, userId: userId);"
$c += "  }"
$c += ""
$c += "  Stream<List<PiggyBankModel>> watch(String familyId) => remote.watch(familyId);"
$c += "}"
WriteDart "$DATA\repositories\piggy_banks_repository_impl.dart" $c

# ============ credit_cards_repository_impl.dart ============
$c = @()
$c += "import '../datasources/credit_cards_remote_datasource.dart';"
$c += "import '../models/credit_card_model.dart';"
$c += "import '../models/invoice_model.dart';"
$c += "import '../../core/errors/failure.dart';"
$c += ""
$c += "class CreditCardsRepositoryImpl {"
$c += "  final CreditCardsRemoteDataSource remote;"
$c += "  CreditCardsRepositoryImpl(this.remote);"
$c += ""
$c += "  Future<List<CreditCardModel>> list(String familyId) => remote.list(familyId);"
$c += ""
$c += "  Future<CreditCardModel> create(CreditCardModel card) async {"
$c += "    if (card.closingDay < 1 || card.closingDay > 31) {"
$c += "      throw const ValidationFailure('Dia de fechamento invalido');"
$c += "    }"
$c += "    if (card.dueDay < 1 || card.dueDay > 31) {"
$c += "      throw const ValidationFailure('Dia de vencimento invalido');"
$c += "    }"
$c += "    if (card.creditLimit <= 0) {"
$c += "      throw const ValidationFailure('Limite deve ser maior que zero');"
$c += "    }"
$c += "    return remote.insert(card);"
$c += "  }"
$c += ""
$c += "  Future<List<InvoiceModel>> getInvoices(String creditCardId) =>"
$c += "      remote.listInvoices(creditCardId);"
$c += ""
$c += "  Future<InvoiceModel?> getCurrentInvoice(String creditCardId) =>"
$c += "      remote.getCurrentInvoice(creditCardId);"
$c += "}"
WriteDart "$DATA\repositories\credit_cards_repository_impl.dart" $c

# ============ categories_repository_impl.dart ============
$c = @()
$c += "import '../datasources/categories_remote_datasource.dart';"
$c += "import '../models/category_model.dart';"
$c += ""
$c += "class CategoriesRepositoryImpl {"
$c += "  final CategoriesRemoteDataSource remote;"
$c += "  CategoriesRepositoryImpl(this.remote);"
$c += ""
$c += "  Future<List<CategoryModel>> list(String familyId) => remote.list(familyId);"
$c += "}"
WriteDart "$DATA\repositories\categories_repository_impl.dart" $c

# ============ budgets_repository_impl.dart ============
$c = @()
$c += "import '../datasources/budgets_remote_datasource.dart';"
$c += "import '../models/budget_model.dart';"
$c += ""
$c += "class BudgetsRepositoryImpl {"
$c += "  final BudgetsRemoteDataSource remote;"
$c += "  BudgetsRepositoryImpl(this.remote);"
$c += ""
$c += "  /// Filosofia OD: orcamento do mes atual veio da renda de M-2"
$c += "  Future<BudgetModel?> getCurrentMonthBudget(String familyId) =>"
$c += "      remote.getCurrent(familyId);"
$c += ""
$c += "  Future<List<BudgetModel>> getHistory(String familyId) =>"
$c += "      remote.listHistory(familyId);"
$c += "}"
WriteDart "$DATA\repositories\budgets_repository_impl.dart" $c

# ============ goals_repository_impl.dart ============
$c = @()
$c += "import '../datasources/goals_remote_datasource.dart';"
$c += "import '../models/goal_model.dart';"
$c += "import '../../core/errors/failure.dart';"
$c += ""
$c += "class GoalsRepositoryImpl {"
$c += "  final GoalsRemoteDataSource remote;"
$c += "  GoalsRepositoryImpl(this.remote);"
$c += ""
$c += "  Future<List<GoalModel>> list(String familyId) => remote.list(familyId);"
$c += ""
$c += "  Future<GoalModel> create({"
$c += "    required String familyId,"
$c += "    required String name,"
$c += "    required double targetAmount,"
$c += "    DateTime? targetDate,"
$c += "    String? icon,"
$c += "  }) async {"
$c += "    if (targetAmount <= 0) {"
$c += "      throw const ValidationFailure('Valor da meta deve ser maior que zero');"
$c += "    }"
$c += "    return remote.insert({"
$c += "      'family_id': familyId,"
$c += "      'name': name,"
$c += "      'target_amount': targetAmount,"
$c += "      'current_amount': 0,"
$c += "      'target_date': targetDate?.toIso8601String(),"
$c += "      'icon': icon,"
$c += "      'status': 'active',"
$c += "    });"
$c += "  }"
$c += "}"
WriteDart "$DATA\repositories\goals_repository_impl.dart" $c

# ============ Barrel data.dart ============
$c = @()
$c += "// Barrel - data layer"
$c += "// Models"
$c += "export 'models/user_model.dart';"
$c += "export 'models/family_model.dart';"
$c += "export 'models/account_model.dart';"
$c += "export 'models/transaction_model.dart';"
$c += "export 'models/piggy_bank_model.dart';"
$c += "export 'models/credit_card_model.dart';"
$c += "export 'models/invoice_model.dart';"
$c += "export 'models/category_model.dart';"
$c += "export 'models/budget_model.dart';"
$c += "export 'models/goal_model.dart';"
$c += "// DataSources"
$c += "export 'datasources/auth_remote_datasource.dart';"
$c += "export 'datasources/transactions_remote_datasource.dart';"
$c += "export 'datasources/piggy_banks_remote_datasource.dart';"
$c += "export 'datasources/credit_cards_remote_datasource.dart';"
$c += "export 'datasources/categories_remote_datasource.dart';"
$c += "export 'datasources/budgets_remote_datasource.dart';"
$c += "export 'datasources/goals_remote_datasource.dart';"
$c += "// Repositories"
$c += "export 'repositories/auth_repository_impl.dart';"
$c += "export 'repositories/transactions_repository_impl.dart';"
$c += "export 'repositories/piggy_banks_repository_impl.dart';"
$c += "export 'repositories/credit_cards_repository_impl.dart';"
$c += "export 'repositories/categories_repository_impl.dart';"
$c += "export 'repositories/budgets_repository_impl.dart';"
$c += "export 'repositories/goals_repository_impl.dart';"
WriteDart "$DATA\data.dart" $c

# ============ Resumo ============
$totalFiles = (Get-ChildItem -Path $DATA -Recurse -File -Filter "*.dart").Count
Log "" "White"
Log "================================================================" "Cyan"
Log " RESUMO" "Cyan"
Log "================================================================" "Cyan"
Log "Arquivos .dart criados em lib/data: $totalFiles" "Green"
Log "  - Models: 10" "Gray"
Log "  - DataSources: 7" "Gray"
Log "  - Repositories: 7" "Gray"
Log "  - Barrel: 1" "Gray"
Log "================================================================" "Cyan"
Log " SCRIPT 18 - CONCLUIDO" "Cyan"
Log "================================================================" "Cyan"
