$ErrorActionPreference = "Stop"

$ROOT     = "Z:\AppFinancas"
$BASE     = "Z:\AppFinancas\app"
$LIB      = "$BASE\lib"
$DOMAIN   = "$LIB\domain"
$ENT      = "$DOMAIN\entities"
$REPOI    = "$DOMAIN\repositories"
$UC       = "$DOMAIN\usecases"
$LOG_DIR  = "$ROOT\logs"
$LOG_FILE = "$LOG_DIR\19_create_domain_layer.log"

if (-not (Test-Path $LOG_DIR)) { New-Item -ItemType Directory -Path $LOG_DIR -Force | Out-Null }

function Log {
    param([string]$msg, [string]$color = "White")
    $stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[$stamp] $msg"
    Write-Host $line -ForegroundColor $color
    Add-Content -Path $LOG_FILE -Value $line -Encoding utf8
}

function WriteDart {
    param([string]$path, [string[]]$content)
    $dir = Split-Path $path
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllLines($path, $content, $utf8)
    Log ("  ~ " + $path.Replace($ROOT, "")) "Gray"
}

Log "================================================================" "Cyan"
Log " SCRIPT 19 - create_domain_layer" "Cyan"
Log " Entities + Repositories (interfaces) + UseCases" "Cyan"
Log "================================================================" "Cyan"

foreach ($d in @($ENT, $REPOI, $UC)) {
    if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
}

# ================================================================
# 1) ENTITIES
# ================================================================
Log "" "White"
Log "[1/3] Criando entities..." "Yellow"

# ---- transaction.dart ----
$c = @()
$c += "/// Entidade de dominio - Transacao financeira"
$c += "/// Tipos: income (receita), expense (despesa), transfer (transferencia)"
$c += "class Transaction {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final String userId;"
$c += "  final String type;"
$c += "  final double amount;"
$c += "  final String description;"
$c += "  final String? categoryId;"
$c += "  final String? accountId;"
$c += "  final String? creditCardId;"
$c += "  final String? invoiceId;"
$c += "  final String? piggyBankId;"
$c += "  final DateTime date;"
$c += "  final bool isInstallment;"
$c += "  final int? installmentNumber;"
$c += "  final int? totalInstallments;"
$c += "  final String? parentTransactionId;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const Transaction({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.userId,"
$c += "    required this.type,"
$c += "    required this.amount,"
$c += "    required this.description,"
$c += "    required this.date,"
$c += "    required this.createdAt,"
$c += "    this.categoryId,"
$c += "    this.accountId,"
$c += "    this.creditCardId,"
$c += "    this.invoiceId,"
$c += "    this.piggyBankId,"
$c += "    this.isInstallment = false,"
$c += "    this.installmentNumber,"
$c += "    this.totalInstallments,"
$c += "    this.parentTransactionId,"
$c += "  });"
$c += ""
$c += "  bool get isIncome => type == 'income';"
$c += "  bool get isExpense => type == 'expense';"
$c += "  bool get isCreditCardExpense => creditCardId != null;"
$c += "}"
WriteDart "$ENT\transaction.dart" $c

# ---- piggy_bank.dart ----
$c = @()
$c += "/// Entidade de dominio - Caixinha"
$c += "/// Tipos: CF (Caixinha de Fatura), CPI (Caixinha de Parcela Integral),"
$c += "/// CP (Caixinha de Poupanca), CM (Caixinha de Meta), CE (Caixinha de Emergencia)"
$c += "class PiggyBank {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final String name;"
$c += "  final String type;"
$c += "  final double currentBalance;"
$c += "  final double reservedAmount;"
$c += "  final double? targetAmount;"
$c += "  final String? creditCardId;"
$c += "  final String? goalId;"
$c += "  final DateTime? targetDate;"
$c += "  final String color;"
$c += "  final String icon;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const PiggyBank({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.name,"
$c += "    required this.type,"
$c += "    required this.currentBalance,"
$c += "    required this.reservedAmount,"
$c += "    required this.createdAt,"
$c += "    this.targetAmount,"
$c += "    this.creditCardId,"
$c += "    this.goalId,"
$c += "    this.targetDate,"
$c += "    this.color = '#2196F3',"
$c += "    this.icon = 'savings',"
$c += "  });"
$c += ""
$c += "  /// Saldo disponivel = saldo atual - valor reservado"
$c += "  double get availableBalance => currentBalance - reservedAmount;"
$c += ""
$c += "  /// Progresso 0.0 a 1.0 em direcao a meta"
$c += "  double get progress {"
$c += "    if (targetAmount == null || targetAmount == 0) return 0.0;"
$c += "    final p = currentBalance / targetAmount!;"
$c += "    return p > 1.0 ? 1.0 : p;"
$c += "  }"
$c += ""
$c += "  bool get isCaixinhaFatura => type == 'CF';"
$c += "  bool get isCaixinhaParcelaIntegral => type == 'CPI';"
$c += "  bool get isCaixinhaEmergencia => type == 'CE';"
$c += "}"
WriteDart "$ENT\piggy_bank.dart" $c

# ---- credit_card.dart ----
$c = @()
$c += "class CreditCard {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final String name;"
$c += "  final String? lastDigits;"
$c += "  final double limit;"
$c += "  final int closingDay;"
$c += "  final int dueDay;"
$c += "  final String? piggyBankCfId;"
$c += "  final String color;"
$c += "  final String brand;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const CreditCard({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.name,"
$c += "    required this.limit,"
$c += "    required this.closingDay,"
$c += "    required this.dueDay,"
$c += "    required this.createdAt,"
$c += "    this.lastDigits,"
$c += "    this.piggyBankCfId,"
$c += "    this.color = '#1976D2',"
$c += "    this.brand = 'generic',"
$c += "  });"
$c += "}"
WriteDart "$ENT\credit_card.dart" $c

# ---- invoice.dart ----
$c = @()
$c += "class Invoice {"
$c += "  final String id;"
$c += "  final String creditCardId;"
$c += "  final int referenceMonth;"
$c += "  final int referenceYear;"
$c += "  final DateTime closingDate;"
$c += "  final DateTime dueDate;"
$c += "  final double totalAmount;"
$c += "  final double paidAmount;"
$c += "  final String status;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const Invoice({"
$c += "    required this.id,"
$c += "    required this.creditCardId,"
$c += "    required this.referenceMonth,"
$c += "    required this.referenceYear,"
$c += "    required this.closingDate,"
$c += "    required this.dueDate,"
$c += "    required this.totalAmount,"
$c += "    required this.paidAmount,"
$c += "    required this.status,"
$c += "    required this.createdAt,"
$c += "  });"
$c += ""
$c += "  double get remainingAmount => totalAmount - paidAmount;"
$c += "  bool get isPaid => status == 'paid';"
$c += "  bool get isOpen => status == 'open';"
$c += "  bool get isClosed => status == 'closed';"
$c += "}"
WriteDart "$ENT\invoice.dart" $c

# ---- budget.dart ----
$c = @()
$c += "/// Entidade Orcamento Mensal (OD - Orcamento Defasado)"
$c += "/// Renda do mes M define orcamento de M+2"
$c += "class Budget {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final int referenceMonth;"
$c += "  final int referenceYear;"
$c += "  final double totalIncomeSource;"
$c += "  final int sourceMonth;"
$c += "  final int sourceYear;"
$c += "  final double essentialBudget;"
$c += "  final double lifestyleBudget;"
$c += "  final double savingsBudget;"
$c += "  final double essentialSpent;"
$c += "  final double lifestyleSpent;"
$c += "  final double savingsSpent;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const Budget({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.referenceMonth,"
$c += "    required this.referenceYear,"
$c += "    required this.totalIncomeSource,"
$c += "    required this.sourceMonth,"
$c += "    required this.sourceYear,"
$c += "    required this.essentialBudget,"
$c += "    required this.lifestyleBudget,"
$c += "    required this.savingsBudget,"
$c += "    required this.essentialSpent,"
$c += "    required this.lifestyleSpent,"
$c += "    required this.savingsSpent,"
$c += "    required this.createdAt,"
$c += "  });"
$c += ""
$c += "  double get totalBudget => essentialBudget + lifestyleBudget + savingsBudget;"
$c += "  double get totalSpent => essentialSpent + lifestyleSpent + savingsSpent;"
$c += "  double get remaining => totalBudget - totalSpent;"
$c += ""
$c += "  double get essentialProgress => essentialBudget == 0 ? 0 : essentialSpent / essentialBudget;"
$c += "  double get lifestyleProgress => lifestyleBudget == 0 ? 0 : lifestyleSpent / lifestyleBudget;"
$c += "  double get savingsProgress => savingsBudget == 0 ? 0 : savingsSpent / savingsBudget;"
$c += "}"
WriteDart "$ENT\budget.dart" $c

# ---- goal.dart ----
$c = @()
$c += "class Goal {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final String name;"
$c += "  final String? description;"
$c += "  final double targetAmount;"
$c += "  final double currentAmount;"
$c += "  final DateTime? targetDate;"
$c += "  final String? piggyBankId;"
$c += "  final String status;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const Goal({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.name,"
$c += "    required this.targetAmount,"
$c += "    required this.currentAmount,"
$c += "    required this.status,"
$c += "    required this.createdAt,"
$c += "    this.description,"
$c += "    this.targetDate,"
$c += "    this.piggyBankId,"
$c += "  });"
$c += ""
$c += "  double get progress {"
$c += "    if (targetAmount == 0) return 0;"
$c += "    final p = currentAmount / targetAmount;"
$c += "    return p > 1.0 ? 1.0 : p;"
$c += "  }"
$c += ""
$c += "  bool get isCompleted => currentAmount >= targetAmount;"
$c += "}"
WriteDart "$ENT\goal.dart" $c

# ---- category.dart ----
$c = @()
$c += "class Category {"
$c += "  final String id;"
$c += "  final String? familyId;"
$c += "  final String name;"
$c += "  final String type;"
$c += "  final String? group;"
$c += "  final String icon;"
$c += "  final String color;"
$c += "  final bool isDefault;"
$c += ""
$c += "  const Category({"
$c += "    required this.id,"
$c += "    required this.name,"
$c += "    required this.type,"
$c += "    this.familyId,"
$c += "    this.group,"
$c += "    this.icon = 'category',"
$c += "    this.color = '#9E9E9E',"
$c += "    this.isDefault = false,"
$c += "  });"
$c += ""
$c += "  bool get isEssential => group == 'essential';"
$c += "  bool get isLifestyle => group == 'lifestyle';"
$c += "  bool get isSavings => group == 'savings';"
$c += "}"
WriteDart "$ENT\category.dart" $c

# ---- user_profile.dart ----
$c = @()
$c += "class UserProfile {"
$c += "  final String id;"
$c += "  final String familyId;"
$c += "  final String email;"
$c += "  final String name;"
$c += "  final String? avatarUrl;"
$c += "  final String role;"
$c += "  final DateTime createdAt;"
$c += ""
$c += "  const UserProfile({"
$c += "    required this.id,"
$c += "    required this.familyId,"
$c += "    required this.email,"
$c += "    required this.name,"
$c += "    required this.role,"
$c += "    required this.createdAt,"
$c += "    this.avatarUrl,"
$c += "  });"
$c += "}"
WriteDart "$ENT\user_profile.dart" $c

# ================================================================
# 2) REPOSITORY INTERFACES
# ================================================================
Log "" "White"
Log "[2/3] Criando interfaces de repository..." "Yellow"

# ---- i_transactions_repository.dart ----
$c = @()
$c += "import '../entities/transaction.dart';"
$c += ""
$c += "abstract class ITransactionsRepository {"
$c += "  Future<List<Transaction>> listByMonth({"
$c += "    required String familyId,"
$c += "    required int month,"
$c += "    required int year,"
$c += "  });"
$c += "  Future<Transaction> create(Transaction t);"
$c += "  Future<Transaction> update(String id, Map<String, dynamic> fields);"
$c += "  Future<void> delete(String id);"
$c += "  Stream<List<Transaction>> watchByFamily(String familyId);"
$c += "}"
WriteDart "$REPOI\i_transactions_repository.dart" $c

# ---- i_piggy_banks_repository.dart ----
$c = @()
$c += "import '../entities/piggy_bank.dart';"
$c += ""
$c += "abstract class IPiggyBanksRepository {"
$c += "  Future<List<PiggyBank>> list(String familyId);"
$c += "  Future<PiggyBank> create(PiggyBank piggyBank);"
$c += "  Future<void> contribute({"
$c += "    required String piggyBankId,"
$c += "    required double amount,"
$c += "    required String userId,"
$c += "  });"
$c += "  Stream<List<PiggyBank>> watch(String familyId);"
$c += "}"
WriteDart "$REPOI\i_piggy_banks_repository.dart" $c

# ---- i_credit_cards_repository.dart ----
$c = @()
$c += "import '../entities/credit_card.dart';"
$c += "import '../entities/invoice.dart';"
$c += ""
$c += "abstract class ICreditCardsRepository {"
$c += "  Future<List<CreditCard>> list(String familyId);"
$c += "  Future<CreditCard> create(CreditCard card);"
$c += "  Future<List<Invoice>> listInvoices(String creditCardId);"
$c += "  Future<Invoice?> getCurrentInvoice(String creditCardId);"
$c += "}"
WriteDart "$REPOI\i_credit_cards_repository.dart" $c

# ---- i_budgets_repository.dart ----
$c = @()
$c += "import '../entities/budget.dart';"
$c += ""
$c += "abstract class IBudgetsRepository {"
$c += "  Future<Budget?> getCurrent(String familyId);"
$c += "  Future<List<Budget>> listHistory(String familyId, {int limit});"
$c += "}"
WriteDart "$REPOI\i_budgets_repository.dart" $c

# ---- i_goals_repository.dart ----
$c = @()
$c += "import '../entities/goal.dart';"
$c += ""
$c += "abstract class IGoalsRepository {"
$c += "  Future<List<Goal>> list(String familyId);"
$c += "  Future<Goal> create(Map<String, dynamic> data);"
$c += "}"
WriteDart "$REPOI\i_goals_repository.dart" $c

# ---- i_categories_repository.dart ----
$c = @()
$c += "import '../entities/category.dart';"
$c += ""
$c += "abstract class ICategoriesRepository {"
$c += "  Future<List<Category>> list(String familyId);"
$c += "}"
WriteDart "$REPOI\i_categories_repository.dart" $c

# ---- i_auth_repository.dart ----
$c = @()
$c += "import '../entities/user_profile.dart';"
$c += ""
$c += "abstract class IAuthRepository {"
$c += "  Future<UserProfile?> signIn(String email, String password);"
$c += "  Future<UserProfile?> signUp({"
$c += "    required String email,"
$c += "    required String password,"
$c += "    required String name,"
$c += "  });"
$c += "  Future<void> signOut();"
$c += "  Future<UserProfile?> getCurrentUserProfile();"
$c += "  Stream<UserProfile?> get userChanges;"
$c += "}"
WriteDart "$REPOI\i_auth_repository.dart" $c

# ================================================================
# 3) USE CASES (regras OD/CF/CPI)
# ================================================================
Log "" "White"
Log "[3/3] Criando use cases (OD/CF/CPI)..." "Yellow"

# ---- create_transaction_usecase.dart ----
$c = @()
$c += "import '../entities/transaction.dart';"
$c += "import '../repositories/i_transactions_repository.dart';"
$c += "import '../repositories/i_piggy_banks_repository.dart';"
$c += "import '../../core/errors/failure.dart';"
$c += ""
$c += "/// Use Case - Criar transacao com regras CF aplicadas"
$c += "/// REGRA CF: Toda despesa em cartao de credito reserva o valor"
$c += "/// imediatamente na Caixinha de Fatura do cartao."
$c += "class CreateTransactionUseCase {"
$c += "  final ITransactionsRepository transactionsRepo;"
$c += "  final IPiggyBanksRepository piggyBanksRepo;"
$c += ""
$c += "  CreateTransactionUseCase({"
$c += "    required this.transactionsRepo,"
$c += "    required this.piggyBanksRepo,"
$c += "  });"
$c += ""
$c += "  Future<Transaction> call(Transaction t) async {"
$c += "    if (t.amount <= 0) {"
$c += "      throw const ValidationFailure('Valor deve ser maior que zero');"
$c += "    }"
$c += "    if (t.description.trim().isEmpty) {"
$c += "      throw const ValidationFailure('Descricao obrigatoria');"
$c += "    }"
$c += ""
$c += "    // A reserva CF e feita por trigger no banco (Script 14)"
$c += "    // Aqui apenas garantimos a integridade dos dados"
$c += "    if (t.isCreditCardExpense && t.creditCardId == null) {"
$c += "      throw const BusinessRuleFailure('Despesa de cartao precisa de credit_card_id');"
$c += "    }"
$c += ""
$c += "    return transactionsRepo.create(t);"
$c += "  }"
$c += "}"
WriteDart "$UC\create_transaction_usecase.dart" $c

# ---- create_installment_purchase_usecase.dart ----
$c = @()
$c += "import '../entities/transaction.dart';"
$c += "import '../entities/piggy_bank.dart';"
$c += "import '../repositories/i_transactions_repository.dart';"
$c += "import '../repositories/i_piggy_banks_repository.dart';"
$c += "import '../../core/errors/failure.dart';"
$c += ""
$c += "/// Use Case - Compra Parcelada (CPI - Caixinha de Parcela Integral)"
$c += "/// REGRA CPI: Compra parcelada reserva o VALOR TOTAL no ato em uma CPI."
$c += "/// As parcelas sao pagas mes a mes pela CF do cartao."
$c += "class CreateInstallmentPurchaseUseCase {"
$c += "  final ITransactionsRepository transactionsRepo;"
$c += "  final IPiggyBanksRepository piggyBanksRepo;"
$c += ""
$c += "  CreateInstallmentPurchaseUseCase({"
$c += "    required this.transactionsRepo,"
$c += "    required this.piggyBanksRepo,"
$c += "  });"
$c += ""
$c += "  Future<void> call({"
$c += "    required String familyId,"
$c += "    required String userId,"
$c += "    required String creditCardId,"
$c += "    required String description,"
$c += "    required double totalAmount,"
$c += "    required int installments,"
$c += "    required DateTime purchaseDate,"
$c += "    String? categoryId,"
$c += "  }) async {"
$c += "    if (totalAmount <= 0) {"
$c += "      throw const ValidationFailure('Valor total deve ser maior que zero');"
$c += "    }"
$c += "    if (installments < 2) {"
$c += "      throw const ValidationFailure('Parcelado precisa ter ao menos 2 parcelas');"
$c += "    }"
$c += "    if (installments > 60) {"
$c += "      throw const ValidationFailure('Maximo 60 parcelas');"
$c += "    }"
$c += ""
$c += "    // 1. Cria CPI com valor TOTAL ja reservado (regra CPI)"
$c += "    final cpi = PiggyBank("
$c += "      id: '',"
$c += "      familyId: familyId,"
$c += "      name: 'CPI: ' + description,"
$c += "      type: 'CPI',"
$c += "      currentBalance: totalAmount,"
$c += "      reservedAmount: totalAmount,"
$c += "      targetAmount: totalAmount,"
$c += "      createdAt: DateTime.now(),"
$c += "      color: '#FF9800',"
$c += "      icon: 'shopping_cart',"
$c += "    );"
$c += "    final createdCpi = await piggyBanksRepo.create(cpi);"
$c += ""
$c += "    // 2. Cria transacao-pai (compra original)"
$c += "    final parent = Transaction("
$c += "      id: '',"
$c += "      familyId: familyId,"
$c += "      userId: userId,"
$c += "      type: 'expense',"
$c += "      amount: totalAmount,"
$c += "      description: description,"
$c += "      date: purchaseDate,"
$c += "      createdAt: DateTime.now(),"
$c += "      categoryId: categoryId,"
$c += "      creditCardId: creditCardId,"
$c += "      piggyBankId: createdCpi.id,"
$c += "      isInstallment: true,"
$c += "      totalInstallments: installments,"
$c += "      installmentNumber: 0,"
$c += "    );"
$c += "    await transactionsRepo.create(parent);"
$c += ""
$c += "    // Obs: as parcelas individuais sao geradas pelo trigger no banco"
$c += "    // (Script 14 - create_triggers)"
$c += "  }"
$c += "}"
WriteDart "$UC\create_installment_purchase_usecase.dart" $c

# ---- calculate_orcamento_defasado_usecase.dart ----
$c = @()
$c += "/// Use Case - Calculo do Orcamento Defasado (OD)"
$c += "/// REGRA OD: Renda do mes M define o orcamento do mes M+2."
$c += "/// Ex: Renda recebida em Janeiro -> orcamento de Marco."
$c += "class CalculateOrcamentoDefasadoUseCase {"
$c += "  /// Retorna o mes/ano de origem da renda que define o orcamento do mes alvo."
$c += "  /// targetMonth/targetYear = mes que sera orcado."
$c += "  /// Retorna {month, year} = mes M-2 cuja renda define este orcamento."
$c += "  Map<String, int> getSourceMonth({"
$c += "    required int targetMonth,"
$c += "    required int targetYear,"
$c += "  }) {"
$c += "    int sm = targetMonth - 2;"
$c += "    int sy = targetYear;"
$c += "    if (sm <= 0) {"
$c += "      sm += 12;"
$c += "      sy -= 1;"
$c += "    }"
$c += "    return {'month': sm, 'year': sy};"
$c += "  }"
$c += ""
$c += "  /// Aplica regra 50/30/20:"
$c += "  /// 50% essencial / 30% estilo de vida / 20% poupanca+metas"
$c += "  Map<String, double> split503020(double totalIncome) {"
$c += "    return {"
$c += "      'essential': totalIncome * 0.50,"
$c += "      'lifestyle': totalIncome * 0.30,"
$c += "      'savings': totalIncome * 0.20,"
$c += "    };"
$c += "  }"
$c += "}"
WriteDart "$UC\calculate_orcamento_defasado_usecase.dart" $c

# ---- pay_invoice_usecase.dart ----
$c = @()
$c += "import '../entities/invoice.dart';"
$c += "import '../entities/piggy_bank.dart';"
$c += "import '../../core/errors/failure.dart';"
$c += ""
$c += "/// Use Case - Pagamento da fatura usando a CF (Caixinha de Fatura)"
$c += "/// REGRA CF: A CF do cartao paga automaticamente a fatura no vencimento."
$c += "class PayInvoiceUseCase {"
$c += "  /// Valida se ha cobertura suficiente na CF"
$c += "  bool hasCoverage({"
$c += "    required Invoice invoice,"
$c += "    required PiggyBank cf,"
$c += "  }) {"
$c += "    if (!cf.isCaixinhaFatura) {"
$c += "      throw const BusinessRuleFailure('Caixinha precisa ser do tipo CF');"
$c += "    }"
$c += "    return cf.currentBalance >= invoice.remainingAmount;"
$c += "  }"
$c += ""
$c += "  /// Percentual de cobertura 0.0-1.0"
$c += "  double coverageRatio({"
$c += "    required Invoice invoice,"
$c += "    required PiggyBank cf,"
$c += "  }) {"
$c += "    if (invoice.remainingAmount == 0) return 1.0;"
$c += "    final r = cf.currentBalance / invoice.remainingAmount;"
$c += "    return r > 1.0 ? 1.0 : r;"
$c += "  }"
$c += "}"
WriteDart "$UC\pay_invoice_usecase.dart" $c

# ---- calculate_score_paz_financeira_usecase.dart ----
$c = @()
$c += "import '../entities/budget.dart';"
$c += "import '../entities/piggy_bank.dart';"
$c += "import '../entities/invoice.dart';"
$c += ""
$c += "/// Use Case - Score de Paz Financeira (0 a 100)"
$c += "/// Indicador composto que mede a saude financeira do casal."
$c += "/// Componentes:"
$c += "/// - 30 pts: Cobertura da CF sobre faturas em aberto"
$c += "/// - 25 pts: Reserva de Emergencia (CE) >= 3x despesas mensais"
$c += "/// - 20 pts: Aderencia ao orcamento (gasto <= orcado)"
$c += "/// - 15 pts: Progresso nas metas ativas"
$c += "/// - 10 pts: Renda do mes anterior cobre orcamento atual (OD)"
$c += "class CalculateScorePazFinanceiraUseCase {"
$c += "  double call({"
$c += "    required List<PiggyBank> piggyBanks,"
$c += "    required List<Invoice> openInvoices,"
$c += "    required Budget? currentBudget,"
$c += "    required double monthlyExpenses,"
$c += "    required double goalsProgress,"
$c += "    required bool incomeCoversOd,"
$c += "  }) {"
$c += "    double score = 0;"
$c += ""
$c += "    // 1. Cobertura CF (30 pts)"
$c += "    final cfs = piggyBanks.where((p) => p.isCaixinhaFatura).toList();"
$c += "    final totalCf = cfs.fold<double>(0, (s, p) => s + p.currentBalance);"
$c += "    final totalOpen = openInvoices.fold<double>(0, (s, i) => s + i.remainingAmount);"
$c += "    if (totalOpen == 0) {"
$c += "      score += 30;"
$c += "    } else {"
$c += "      final ratio = (totalCf / totalOpen).clamp(0.0, 1.0);"
$c += "      score += ratio * 30;"
$c += "    }"
$c += ""
$c += "    // 2. Reserva de Emergencia (25 pts) - meta: 3x despesas mensais"
$c += "    final ces = piggyBanks.where((p) => p.isCaixinhaEmergencia).toList();"
$c += "    final totalCe = ces.fold<double>(0, (s, p) => s + p.currentBalance);"
$c += "    if (monthlyExpenses > 0) {"
$c += "      final ratio = (totalCe / (monthlyExpenses * 3)).clamp(0.0, 1.0);"
$c += "      score += ratio * 25;"
$c += "    }"
$c += ""
$c += "    // 3. Aderencia ao orcamento (20 pts)"
$c += "    if (currentBudget != null && currentBudget.totalBudget > 0) {"
$c += "      final overrun = currentBudget.totalSpent / currentBudget.totalBudget;"
$c += "      if (overrun <= 1.0) {"
$c += "        score += 20;"
$c += "      } else if (overrun <= 1.2) {"
$c += "        score += 10;"
$c += "      }"
$c += "    }"
$c += ""
$c += "    // 4. Progresso de metas (15 pts)"
$c += "    score += goalsProgress.clamp(0.0, 1.0) * 15;"
$c += ""
$c += "    // 5. OD - renda do mes anterior cobre orcamento (10 pts)"
$c += "    if (incomeCoversOd) score += 10;"
$c += ""
$c += "    return score.clamp(0.0, 100.0);"
$c += "  }"
$c += "}"
WriteDart "$UC\calculate_score_paz_financeira_usecase.dart" $c

# ---- contribute_to_caixinha_usecase.dart ----
$c = @()
$c += "import '../repositories/i_piggy_banks_repository.dart';"
$c += "import '../../core/errors/failure.dart';"
$c += ""
$c += "class ContributeToCaixinhaUseCase {"
$c += "  final IPiggyBanksRepository repo;"
$c += "  ContributeToCaixinhaUseCase(this.repo);"
$c += ""
$c += "  Future<void> call({"
$c += "    required String piggyBankId,"
$c += "    required double amount,"
$c += "    required String userId,"
$c += "  }) async {"
$c += "    if (amount <= 0) {"
$c += "      throw const ValidationFailure('Valor deve ser maior que zero');"
$c += "    }"
$c += "    if (amount > 1000000) {"
$c += "      throw const ValidationFailure('Valor excede limite por contribuicao');"
$c += "    }"
$c += "    return repo.contribute(piggyBankId: piggyBankId, amount: amount, userId: userId);"
$c += "  }"
$c += "}"
WriteDart "$UC\contribute_to_caixinha_usecase.dart" $c

# ---- check_budget_alerts_usecase.dart ----
$c = @()
$c += "import '../entities/budget.dart';"
$c += ""
$c += "/// Use Case - Verifica alertas de orcamento"
$c += "/// Niveis: ok, warning (>=80%), danger (>=100%)"
$c += "class CheckBudgetAlertsUseCase {"
$c += "  List<BudgetAlert> call(Budget budget) {"
$c += "    final alerts = <BudgetAlert>[];"
$c += ""
$c += "    void check(String group, double spent, double budgetValue) {"
$c += "      if (budgetValue == 0) return;"
$c += "      final ratio = spent / budgetValue;"
$c += "      if (ratio >= 1.0) {"
$c += "        alerts.add(BudgetAlert(group: group, level: 'danger', ratio: ratio));"
$c += "      } else if (ratio >= 0.8) {"
$c += "        alerts.add(BudgetAlert(group: group, level: 'warning', ratio: ratio));"
$c += "      }"
$c += "    }"
$c += ""
$c += "    check('essential', budget.essentialSpent, budget.essentialBudget);"
$c += "    check('lifestyle', budget.lifestyleSpent, budget.lifestyleBudget);"
$c += "    check('savings', budget.savingsSpent, budget.savingsBudget);"
$c += ""
$c += "    return alerts;"
$c += "  }"
$c += "}"
$c += ""
$c += "class BudgetAlert {"
$c += "  final String group;"
$c += "  final String level;"
$c += "  final double ratio;"
$c += "  const BudgetAlert({"
$c += "    required this.group,"
$c += "    required this.level,"
$c += "    required this.ratio,"
$c += "  });"
$c += "}"
WriteDart "$UC\check_budget_alerts_usecase.dart" $c

# ---- sign_in_usecase / sign_up_usecase / sign_out_usecase ----
$c = @()
$c += "import '../entities/user_profile.dart';"
$c += "import '../repositories/i_auth_repository.dart';"
$c += "import '../../core/errors/failure.dart';"
$c += ""
$c += "class SignInUseCase {"
$c += "  final IAuthRepository repo;"
$c += "  SignInUseCase(this.repo);"
$c += ""
$c += "  Future<UserProfile?> call(String email, String password) async {"
$c += "    if (!email.contains('@')) {"
$c += "      throw const ValidationFailure('Email invalido');"
$c += "    }"
$c += "    if (password.length < 6) {"
$c += "      throw const ValidationFailure('Senha precisa ter ao menos 6 caracteres');"
$c += "    }"
$c += "    return repo.signIn(email, password);"
$c += "  }"
$c += "}"
WriteDart "$UC\sign_in_usecase.dart" $c

$c = @()
$c += "import '../entities/user_profile.dart';"
$c += "import '../repositories/i_auth_repository.dart';"
$c += "import '../../core/errors/failure.dart';"
$c += ""
$c += "class SignUpUseCase {"
$c += "  final IAuthRepository repo;"
$c += "  SignUpUseCase(this.repo);"
$c += ""
$c += "  Future<UserProfile?> call({"
$c += "    required String email,"
$c += "    required String password,"
$c += "    required String name,"
$c += "  }) async {"
$c += "    if (!email.contains('@')) {"
$c += "      throw const ValidationFailure('Email invalido');"
$c += "    }"
$c += "    if (password.length < 6) {"
$c += "      throw const ValidationFailure('Senha precisa ter ao menos 6 caracteres');"
$c += "    }"
$c += "    if (name.trim().isEmpty) {"
$c += "      throw const ValidationFailure('Nome obrigatorio');"
$c += "    }"
$c += "    return repo.signUp(email: email, password: password, name: name);"
$c += "  }"
$c += "}"
WriteDart "$UC\sign_up_usecase.dart" $c

$c = @()
$c += "import '../repositories/i_auth_repository.dart';"
$c += ""
$c += "class SignOutUseCase {"
$c += "  final IAuthRepository repo;"
$c += "  SignOutUseCase(this.repo);"
$c += ""
$c += "  Future<void> call() => repo.signOut();"
$c += "}"
WriteDart "$UC\sign_out_usecase.dart" $c

# ================================================================
# ANALYZE
# ================================================================
Log "" "White"
Log "================================================================" "Cyan"
Log "Executando flutter analyze lib/domain ..." "Cyan"
Log "================================================================" "Cyan"

Push-Location $BASE
flutter analyze lib/domain
$exitCode = $LASTEXITCODE
Pop-Location

# Contagem
$entCount = (Get-ChildItem $ENT -Filter "*.dart" -ErrorAction SilentlyContinue).Count
$repoCount = (Get-ChildItem $REPOI -Filter "*.dart" -ErrorAction SilentlyContinue).Count
$ucCount = (Get-ChildItem $UC -Filter "*.dart" -ErrorAction SilentlyContinue).Count

Log "" "White"
Log "================================================================" "Cyan"
Log " RESUMO" "Cyan"
Log "================================================================" "Cyan"
Log ("Entities criadas:     " + $entCount) "Gray"
Log ("Repositories (i_):    " + $repoCount) "Gray"
Log ("Use Cases:            " + $ucCount) "Gray"

if ($exitCode -eq 0) {
    Log "" "White"
    Log "SCRIPT 19 - SUCESSO TOTAL" "Green"
} else {
    Log "" "White"
    Log "SCRIPT 19 - Concluido com avisos (ver acima)" "Yellow"
}
