$ErrorActionPreference = "Stop"

$ROOT     = "Z:\AppFinancas"
$BASE     = "Z:\AppFinancas\app"
$LIB      = "$BASE\lib"
$PRES     = "$LIB\presentation"
$AUTH     = "$PRES\features\auth"
$PROVIDERS= "$AUTH\providers"
$SCREENS  = "$AUTH\screens"
$WIDGETS  = "$AUTH\widgets"
$ROUTER   = "$PRES\router"
$LOG_DIR  = "$ROOT\logs"
$LOG_FILE = "$LOG_DIR\20_create_auth_feature.log"

if (-not (Test-Path $LOG_DIR)) { New-Item -ItemType Directory -Path $LOG_DIR -Force | Out-Null }

function Log {
    param([string]$msg, [string]$color = "White")
    $stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[$stamp] $msg"
    Write-Host $line -ForegroundColor $color
    Add-Content -Path $LOG_FILE -Value $line -Encoding utf8
}

function WriteDart {
    param([string]$path, [string[]]$content)
    $dir = Split-Path $path
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllLines($path, $content, $utf8)
    Log ("  ~ " + $path.Replace($ROOT, "")) "Gray"
}

Log "================================================================" "Cyan"
Log " SCRIPT 20 - create_auth_feature" "Cyan"
Log " Providers + Screens + Widgets + Router + main.dart" "Cyan"
Log "================================================================" "Cyan"

foreach ($d in @($PROVIDERS, $SCREENS, $WIDGETS, $ROUTER)) {
    if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
}

# ================================================================
# 1) PROVIDERS
# ================================================================
Log "" "White"
Log "[1/5] Criando providers Riverpod..." "Yellow"

# ---- auth_providers.dart ----
$c = @()
$c += "import 'package:flutter_riverpod/flutter_riverpod.dart';"
$c += "import 'package:supabase_flutter/supabase_flutter.dart';"
$c += ""
$c += "import '../../../../data/datasources/supabase_auth_datasource.dart';"
$c += "import '../../../../data/repositories/auth_repository_impl.dart';"
$c += "import '../../../../domain/repositories/i_auth_repository.dart';"
$c += "import '../../../../domain/usecases/sign_in_usecase.dart';"
$c += "import '../../../../domain/usecases/sign_up_usecase.dart';"
$c += "import '../../../../domain/usecases/sign_out_usecase.dart';"
$c += ""
$c += "/// Cliente Supabase global"
$c += "final supabaseClientProvider = Provider<SupabaseClient>((ref) {"
$c += "  return Supabase.instance.client;"
$c += "});"
$c += ""
$c += "/// DataSource"
$c += "final authDataSourceProvider = Provider<SupabaseAuthDataSource>((ref) {"
$c += "  return SupabaseAuthDataSource(ref.watch(supabaseClientProvider));"
$c += "});"
$c += ""
$c += "/// Repository"
$c += "final authRepositoryProvider = Provider<IAuthRepository>((ref) {"
$c += "  return AuthRepositoryImpl(ref.watch(authDataSourceProvider));"
$c += "});"
$c += ""
$c += "/// Use Cases"
$c += "final signInUseCaseProvider = Provider<SignInUseCase>((ref) {"
$c += "  return SignInUseCase(ref.watch(authRepositoryProvider));"
$c += "});"
$c += ""
$c += "final signUpUseCaseProvider = Provider<SignUpUseCase>((ref) {"
$c += "  return SignUpUseCase(ref.watch(authRepositoryProvider));"
$c += "});"
$c += ""
$c += "final signOutUseCaseProvider = Provider<SignOutUseCase>((ref) {"
$c += "  return SignOutUseCase(ref.watch(authRepositoryProvider));"
$c += "});"
WriteDart "$PROVIDERS\auth_providers.dart" $c

# ---- auth_state.dart ----
$c = @()
$c += "import '../../../../domain/entities/user_profile.dart';"
$c += ""
$c += "sealed class AuthState {"
$c += "  const AuthState();"
$c += "}"
$c += ""
$c += "class AuthInitial extends AuthState {"
$c += "  const AuthInitial();"
$c += "}"
$c += ""
$c += "class AuthLoading extends AuthState {"
$c += "  const AuthLoading();"
$c += "}"
$c += ""
$c += "class AuthAuthenticated extends AuthState {"
$c += "  final UserProfile user;"
$c += "  const AuthAuthenticated(this.user);"
$c += "}"
$c += ""
$c += "class AuthUnauthenticated extends AuthState {"
$c += "  const AuthUnauthenticated();"
$c += "}"
$c += ""
$c += "class AuthError extends AuthState {"
$c += "  final String message;"
$c += "  const AuthError(this.message);"
$c += "}"
WriteDart "$PROVIDERS\auth_state.dart" $c

# ---- auth_notifier.dart ----
$c = @()
$c += "import 'package:flutter_riverpod/flutter_riverpod.dart';"
$c += ""
$c += "import '../../../../core/errors/failure.dart';"
$c += "import 'auth_providers.dart';"
$c += "import 'auth_state.dart';"
$c += ""
$c += "class AuthNotifier extends StateNotifier<AuthState> {"
$c += "  final Ref ref;"
$c += "  AuthNotifier(this.ref) : super(const AuthInitial()) {"
$c += "    _bootstrap();"
$c += "  }"
$c += ""
$c += "  Future<void> _bootstrap() async {"
$c += "    state = const AuthLoading();"
$c += "    try {"
$c += "      final repo = ref.read(authRepositoryProvider);"
$c += "      final user = await repo.getCurrentUserProfile();"
$c += "      state = user != null ? AuthAuthenticated(user) : const AuthUnauthenticated();"
$c += "    } catch (_) {"
$c += "      state = const AuthUnauthenticated();"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<void> signIn(String email, String password) async {"
$c += "    state = const AuthLoading();"
$c += "    try {"
$c += "      final useCase = ref.read(signInUseCaseProvider);"
$c += "      final user = await useCase(email, password);"
$c += "      state = user != null ? AuthAuthenticated(user) : const AuthError('Credenciais invalidas');"
$c += "    } on Failure catch (f) {"
$c += "      state = AuthError(f.message);"
$c += "    } catch (e) {"
$c += "      state = AuthError(e.toString());"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<void> signUp({"
$c += "    required String email,"
$c += "    required String password,"
$c += "    required String name,"
$c += "  }) async {"
$c += "    state = const AuthLoading();"
$c += "    try {"
$c += "      final useCase = ref.read(signUpUseCaseProvider);"
$c += "      final user = await useCase(email: email, password: password, name: name);"
$c += "      state = user != null ? AuthAuthenticated(user) : const AuthError('Falha ao cadastrar');"
$c += "    } on Failure catch (f) {"
$c += "      state = AuthError(f.message);"
$c += "    } catch (e) {"
$c += "      state = AuthError(e.toString());"
$c += "    }"
$c += "  }"
$c += ""
$c += "  Future<void> signOut() async {"
$c += "    state = const AuthLoading();"
$c += "    try {"
$c += "      await ref.read(signOutUseCaseProvider).call();"
$c += "      state = const AuthUnauthenticated();"
$c += "    } catch (e) {"
$c += "      state = AuthError(e.toString());"
$c += "    }"
$c += "  }"
$c += "}"
$c += ""
$c += "final authNotifierProvider = StateNotifierProvider<AuthNotifier, AuthState>((ref) {"
$c += "  return AuthNotifier(ref);"
$c += "});"
WriteDart "$PROVIDERS\auth_notifier.dart" $c

# ================================================================
# 2) WIDGETS
# ================================================================
Log "" "White"
Log "[2/5] Criando widgets reutilizaveis..." "Yellow"

# ---- auth_text_field.dart ----
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += ""
$c += "class AuthTextField extends StatelessWidget {"
$c += "  final TextEditingController controller;"
$c += "  final String label;"
$c += "  final IconData icon;"
$c += "  final bool obscureText;"
$c += "  final TextInputType keyboardType;"
$c += "  final String? Function(String?)? validator;"
$c += "  final Widget? suffixIcon;"
$c += ""
$c += "  const AuthTextField({"
$c += "    super.key,"
$c += "    required this.controller,"
$c += "    required this.label,"
$c += "    required this.icon,"
$c += "    this.obscureText = false,"
$c += "    this.keyboardType = TextInputType.text,"
$c += "    this.validator,"
$c += "    this.suffixIcon,"
$c += "  });"
$c += ""
$c += "  @override"
$c += "  Widget build(BuildContext context) {"
$c += "    return TextFormField("
$c += "      controller: controller,"
$c += "      obscureText: obscureText,"
$c += "      keyboardType: keyboardType,"
$c += "      validator: validator,"
$c += "      decoration: InputDecoration("
$c += "        labelText: label,"
$c += "        prefixIcon: Icon(icon),"
$c += "        suffixIcon: suffixIcon,"
$c += "        border: OutlineInputBorder("
$c += "          borderRadius: BorderRadius.circular(12),"
$c += "        ),"
$c += "      ),"
$c += "    );"
$c += "  }"
$c += "}"
WriteDart "$WIDGETS\auth_text_field.dart" $c

# ---- auth_button.dart ----
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += ""
$c += "class AuthButton extends StatelessWidget {"
$c += "  final String label;"
$c += "  final VoidCallback? onPressed;"
$c += "  final bool isLoading;"
$c += "  final IconData? icon;"
$c += ""
$c += "  const AuthButton({"
$c += "    super.key,"
$c += "    required this.label,"
$c += "    required this.onPressed,"
$c += "    this.isLoading = false,"
$c += "    this.icon,"
$c += "  });"
$c += ""
$c += "  @override"
$c += "  Widget build(BuildContext context) {"
$c += "    return SizedBox("
$c += "      width: double.infinity,"
$c += "      height: 52,"
$c += "      child: FilledButton("
$c += "        onPressed: isLoading ? null : onPressed,"
$c += "        style: FilledButton.styleFrom("
$c += "          shape: RoundedRectangleBorder("
$c += "            borderRadius: BorderRadius.circular(12),"
$c += "          ),"
$c += "        ),"
$c += "        child: isLoading"
$c += "            ? const SizedBox("
$c += "                height: 22,"
$c += "                width: 22,"
$c += "                child: CircularProgressIndicator("
$c += "                  strokeWidth: 2.4,"
$c += "                  color: Colors.white,"
$c += "                ),"
$c += "              )"
$c += "            : Row("
$c += "                mainAxisAlignment: MainAxisAlignment.center,"
$c += "                children: ["
$c += "                  if (icon != null) ..."
$c += "                  ["
$c += "                    Icon(icon, size: 20),"
$c += "                    const SizedBox(width: 8),"
$c += "                  ],"
$c += "                  Text("
$c += "                    label,"
$c += "                    style: const TextStyle("
$c += "                      fontSize: 16,"
$c += "                      fontWeight: FontWeight.w600,"
$c += "                    ),"
$c += "                  ),"
$c += "                ],"
$c += "              ),"
$c += "      ),"
$c += "    );"
$c += "  }"
$c += "}"
WriteDart "$WIDGETS\auth_button.dart" $c

# ---- auth_logo.dart ----
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += ""
$c += "class AuthLogo extends StatelessWidget {"
$c += "  final double size;"
$c += "  const AuthLogo({super.key, this.size = 80});"
$c += ""
$c += "  @override"
$c += "  Widget build(BuildContext context) {"
$c += "    final color = Theme.of(context).colorScheme.primary;"
$c += "    return Column("
$c += "      mainAxisSize: MainAxisSize.min,"
$c += "      children: ["
$c += "        Container("
$c += "          width: size,"
$c += "          height: size,"
$c += "          decoration: BoxDecoration("
$c += "            gradient: LinearGradient("
$c += "              colors: [color, color.withValues(alpha: 0.6)],"
$c += "              begin: Alignment.topLeft,"
$c += "              end: Alignment.bottomRight,"
$c += "            ),"
$c += "            borderRadius: BorderRadius.circular(size / 4),"
$c += "          ),"
$c += "          child: Icon("
$c += "            Icons.favorite_rounded,"
$c += "            color: Colors.white,"
$c += "            size: size * 0.5,"
$c += "          ),"
$c += "        ),"
$c += "        const SizedBox(height: 16),"
$c += "        Text("
$c += "          'DinDinVani&Nani',"
$c += "          style: TextStyle("
$c += "            fontSize: 24,"
$c += "            fontWeight: FontWeight.bold,"
$c += "            color: color,"
$c += "          ),"
$c += "        ),"
$c += "        const SizedBox(height: 4),"
$c += "        Text("
$c += "          'Financas em paz, a dois',"
$c += "          style: TextStyle("
$c += "            fontSize: 13,"
$c += "            color: Colors.grey.shade600,"
$c += "          ),"
$c += "        ),"
$c += "      ],"
$c += "    );"
$c += "  }"
$c += "}"
WriteDart "$WIDGETS\auth_logo.dart" $c

# ================================================================
# 3) SCREENS
# ================================================================
Log "" "White"
Log "[3/5] Criando telas..." "Yellow"

# ---- splash_screen.dart ----
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += "import 'package:flutter_riverpod/flutter_riverpod.dart';"
$c += ""
$c += "import '../widgets/auth_logo.dart';"
$c += ""
$c += "class SplashScreen extends ConsumerWidget {"
$c += "  const SplashScreen({super.key});"
$c += ""
$c += "  @override"
$c += "  Widget build(BuildContext context, WidgetRef ref) {"
$c += "    return const Scaffold("
$c += "      body: Center("
$c += "        child: Column("
$c += "          mainAxisAlignment: MainAxisAlignment.center,"
$c += "          children: ["
$c += "            AuthLogo(size: 100),"
$c += "            SizedBox(height: 32),"
$c += "            CircularProgressIndicator(),"
$c += "          ],"
$c += "        ),"
$c += "      ),"
$c += "    );"
$c += "  }"
$c += "}"
WriteDart "$SCREENS\splash_screen.dart" $c

# ---- login_screen.dart ----
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += "import 'package:flutter_riverpod/flutter_riverpod.dart';"
$c += "import 'package:go_router/go_router.dart';"
$c += ""
$c += "import '../providers/auth_notifier.dart';"
$c += "import '../providers/auth_state.dart';"
$c += "import '../widgets/auth_button.dart';"
$c += "import '../widgets/auth_logo.dart';"
$c += "import '../widgets/auth_text_field.dart';"
$c += ""
$c += "class LoginScreen extends ConsumerStatefulWidget {"
$c += "  const LoginScreen({super.key});"
$c += ""
$c += "  @override"
$c += "  ConsumerState<LoginScreen> createState() => _LoginScreenState();"
$c += "}"
$c += ""
$c += "class _LoginScreenState extends ConsumerState<LoginScreen> {"
$c += "  final _formKey = GlobalKey<FormState>();"
$c += "  final _email = TextEditingController();"
$c += "  final _password = TextEditingController();"
$c += "  bool _obscure = true;"
$c += ""
$c += "  @override"
$c += "  void dispose() {"
$c += "    _email.dispose();"
$c += "    _password.dispose();"
$c += "    super.dispose();"
$c += "  }"
$c += ""
$c += "  Future<void> _submit() async {"
$c += "    if (!_formKey.currentState!.validate()) return;"
$c += "    await ref.read(authNotifierProvider.notifier).signIn("
$c += "          _email.text.trim(),"
$c += "          _password.text,"
$c += "        );"
$c += "  }"
$c += ""
$c += "  @override"
$c += "  Widget build(BuildContext context) {"
$c += "    final state = ref.watch(authNotifierProvider);"
$c += "    final isLoading = state is AuthLoading;"
$c += ""
$c += "    ref.listen<AuthState>(authNotifierProvider, (prev, next) {"
$c += "      if (next is AuthError) {"
$c += "        ScaffoldMessenger.of(context).showSnackBar("
$c += "          SnackBar("
$c += "            content: Text(next.message),"
$c += "            backgroundColor: Colors.red.shade700,"
$c += "          ),"
$c += "        );"
$c += "      }"
$c += "    });"
$c += ""
$c += "    return Scaffold("
$c += "      body: SafeArea("
$c += "        child: Center("
$c += "          child: SingleChildScrollView("
$c += "            padding: const EdgeInsets.all(24),"
$c += "            child: ConstrainedBox("
$c += "              constraints: const BoxConstraints(maxWidth: 420),"
$c += "              child: Form("
$c += "                key: _formKey,"
$c += "                child: Column("
$c += "                  mainAxisSize: MainAxisSize.min,"
$c += "                  children: ["
$c += "                    const AuthLogo(),"
$c += "                    const SizedBox(height: 40),"
$c += "                    AuthTextField("
$c += "                      controller: _email,"
$c += "                      label: 'Email',"
$c += "                      icon: Icons.email_outlined,"
$c += "                      keyboardType: TextInputType.emailAddress,"
$c += "                      validator: (v) {"
$c += "                        if (v == null || v.isEmpty) return 'Informe o email';"
$c += "                        if (!v.contains('@')) return 'Email invalido';"
$c += "                        return null;"
$c += "                      },"
$c += "                    ),"
$c += "                    const SizedBox(height: 16),"
$c += "                    AuthTextField("
$c += "                      controller: _password,"
$c += "                      label: 'Senha',"
$c += "                      icon: Icons.lock_outline,"
$c += "                      obscureText: _obscure,"
$c += "                      suffixIcon: IconButton("
$c += "                        icon: Icon(_obscure ? Icons.visibility_off : Icons.visibility),"
$c += "                        onPressed: () => setState(() => _obscure = !_obscure),"
$c += "                      ),"
$c += "                      validator: (v) {"
$c += "                        if (v == null || v.length < 6) return 'Minimo 6 caracteres';"
$c += "                        return null;"
$c += "                      },"
$c += "                    ),"
$c += "                    const SizedBox(height: 24),"
$c += "                    AuthButton("
$c += "                      label: 'Entrar',"
$c += "                      icon: Icons.login,"
$c += "                      isLoading: isLoading,"
$c += "                      onPressed: _submit,"
$c += "                    ),"
$c += "                    const SizedBox(height: 16),"
$c += "                    TextButton("
$c += "                      onPressed: () => context.go('/signup'),"
$c += "                      child: const Text('Nao tem conta? Cadastre-se'),"
$c += "                    ),"
$c += "                  ],"
$c += "                ),"
$c += "              ),"
$c += "            ),"
$c += "          ),"
$c += "        ),"
$c += "      ),"
$c += "    );"
$c += "  }"
$c += "}"
WriteDart "$SCREENS\login_screen.dart" $c

# ---- signup_screen.dart ----
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += "import 'package:flutter_riverpod/flutter_riverpod.dart';"
$c += "import 'package:go_router/go_router.dart';"
$c += ""
$c += "import '../providers/auth_notifier.dart';"
$c += "import '../providers/auth_state.dart';"
$c += "import '../widgets/auth_button.dart';"
$c += "import '../widgets/auth_logo.dart';"
$c += "import '../widgets/auth_text_field.dart';"
$c += ""
$c += "class SignUpScreen extends ConsumerStatefulWidget {"
$c += "  const SignUpScreen({super.key});"
$c += ""
$c += "  @override"
$c += "  ConsumerState<SignUpScreen> createState() => _SignUpScreenState();"
$c += "}"
$c += ""
$c += "class _SignUpScreenState extends ConsumerState<SignUpScreen> {"
$c += "  final _formKey = GlobalKey<FormState>();"
$c += "  final _name = TextEditingController();"
$c += "  final _email = TextEditingController();"
$c += "  final _password = TextEditingController();"
$c += "  bool _obscure = true;"
$c += ""
$c += "  @override"
$c += "  void dispose() {"
$c += "    _name.dispose();"
$c += "    _email.dispose();"
$c += "    _password.dispose();"
$c += "    super.dispose();"
$c += "  }"
$c += ""
$c += "  Future<void> _submit() async {"
$c += "    if (!_formKey.currentState!.validate()) return;"
$c += "    await ref.read(authNotifierProvider.notifier).signUp("
$c += "          email: _email.text.trim(),"
$c += "          password: _password.text,"
$c += "          name: _name.text.trim(),"
$c += "        );"
$c += "  }"
$c += ""
$c += "  @override"
$c += "  Widget build(BuildContext context) {"
$c += "    final state = ref.watch(authNotifierProvider);"
$c += "    final isLoading = state is AuthLoading;"
$c += ""
$c += "    ref.listen<AuthState>(authNotifierProvider, (prev, next) {"
$c += "      if (next is AuthError) {"
$c += "        ScaffoldMessenger.of(context).showSnackBar("
$c += "          SnackBar("
$c += "            content: Text(next.message),"
$c += "            backgroundColor: Colors.red.shade700,"
$c += "          ),"
$c += "        );"
$c += "      }"
$c += "    });"
$c += ""
$c += "    return Scaffold("
$c += "      appBar: AppBar(title: const Text('Criar conta')),"
$c += "      body: SafeArea("
$c += "        child: Center("
$c += "          child: SingleChildScrollView("
$c += "            padding: const EdgeInsets.all(24),"
$c += "            child: ConstrainedBox("
$c += "              constraints: const BoxConstraints(maxWidth: 420),"
$c += "              child: Form("
$c += "                key: _formKey,"
$c += "                child: Column("
$c += "                  mainAxisSize: MainAxisSize.min,"
$c += "                  children: ["
$c += "                    const AuthLogo(size: 64),"
$c += "                    const SizedBox(height: 32),"
$c += "                    AuthTextField("
$c += "                      controller: _name,"
$c += "                      label: 'Nome',"
$c += "                      icon: Icons.person_outline,"
$c += "                      validator: (v) {"
$c += "                        if (v == null || v.trim().isEmpty) return 'Informe seu nome';"
$c += "                        return null;"
$c += "                      },"
$c += "                    ),"
$c += "                    const SizedBox(height: 16),"
$c += "                    AuthTextField("
$c += "                      controller: _email,"
$c += "                      label: 'Email',"
$c += "                      icon: Icons.email_outlined,"
$c += "                      keyboardType: TextInputType.emailAddress,"
$c += "                      validator: (v) {"
$c += "                        if (v == null || v.isEmpty) return 'Informe o email';"
$c += "                        if (!v.contains('@')) return 'Email invalido';"
$c += "                        return null;"
$c += "                      },"
$c += "                    ),"
$c += "                    const SizedBox(height: 16),"
$c += "                    AuthTextField("
$c += "                      controller: _password,"
$c += "                      label: 'Senha',"
$c += "                      icon: Icons.lock_outline,"
$c += "                      obscureText: _obscure,"
$c += "                      suffixIcon: IconButton("
$c += "                        icon: Icon(_obscure ? Icons.visibility_off : Icons.visibility),"
$c += "                        onPressed: () => setState(() => _obscure = !_obscure),"
$c += "                      ),"
$c += "                      validator: (v) {"
$c += "                        if (v == null || v.length < 6) return 'Minimo 6 caracteres';"
$c += "                        return null;"
$c += "                      },"
$c += "                    ),"
$c += "                    const SizedBox(height: 24),"
$c += "                    AuthButton("
$c += "                      label: 'Cadastrar',"
$c += "                      icon: Icons.person_add,"
$c += "                      isLoading: isLoading,"
$c += "                      onPressed: _submit,"
$c += "                    ),"
$c += "                    const SizedBox(height: 16),"
$c += "                    TextButton("
$c += "                      onPressed: () => context.go('/login'),"
$c += "                      child: const Text('Ja tem conta? Entrar'),"
$c += "                    ),"
$c += "                  ],"
$c += "                ),"
$c += "              ),"
$c += "            ),"
$c += "          ),"
$c += "        ),"
$c += "      ),"
$c += "    );"
$c += "  }"
$c += "}"
WriteDart "$SCREENS\signup_screen.dart" $c

# ---- dashboard_placeholder.dart (provisorio ate Script 21) ----
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += "import 'package:flutter_riverpod/flutter_riverpod.dart';"
$c += ""
$c += "import '../providers/auth_notifier.dart';"
$c += "import '../providers/auth_state.dart';"
$c += ""
$c += "/// Tela placeholder do dashboard ate o Script 21 implementar a versao real."
$c += "class DashboardPlaceholderScreen extends ConsumerWidget {"
$c += "  const DashboardPlaceholderScreen({super.key});"
$c += ""
$c += "  @override"
$c += "  Widget build(BuildContext context, WidgetRef ref) {"
$c += "    final state = ref.watch(authNotifierProvider);"
$c += "    final name = state is AuthAuthenticated ? state.user.name : '';"
$c += ""
$c += "    return Scaffold("
$c += "      appBar: AppBar("
$c += "        title: const Text('DinDinVani&Nani'),"
$c += "        actions: ["
$c += "          IconButton("
$c += "            icon: const Icon(Icons.logout),"
$c += "            onPressed: () => ref.read(authNotifierProvider.notifier).signOut(),"
$c += "            tooltip: 'Sair',"
$c += "          ),"
$c += "        ],"
$c += "      ),"
$c += "      body: Center("
$c += "        child: Column("
$c += "          mainAxisAlignment: MainAxisAlignment.center,"
$c += "          children: ["
$c += "            const Icon(Icons.celebration, size: 80, color: Colors.green),"
$c += "            const SizedBox(height: 24),"
$c += "            Text('Bem-vindo(a), \$name!', style: Theme.of(context).textTheme.headlineSmall),"
$c += "            const SizedBox(height: 12),"
$c += "            const Text('Dashboard sera implementado no Script 21'),"
$c += "          ],"
$c += "        ),"
$c += "      ),"
$c += "    );"
$c += "  }"
$c += "}"
WriteDart "$SCREENS\dashboard_placeholder.dart" $c

# ================================================================
# 4) ROUTER
# ================================================================
Log "" "White"
Log "[4/5] Criando router com guards..." "Yellow"

# ---- app_router.dart ----
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += "import 'package:flutter_riverpod/flutter_riverpod.dart';"
$c += "import 'package:go_router/go_router.dart';"
$c += ""
$c += "import '../features/auth/providers/auth_notifier.dart';"
$c += "import '../features/auth/providers/auth_state.dart';"
$c += "import '../features/auth/screens/dashboard_placeholder.dart';"
$c += "import '../features/auth/screens/login_screen.dart';"
$c += "import '../features/auth/screens/signup_screen.dart';"
$c += "import '../features/auth/screens/splash_screen.dart';"
$c += ""
$c += "/// Listener que dispara refresh do router quando o auth state muda"
$c += "class _AuthRouterListener extends ChangeNotifier {"
$c += "  _AuthRouterListener(Ref ref) {"
$c += "    ref.listen<AuthState>(authNotifierProvider, (_, __) => notifyListeners());"
$c += "  }"
$c += "}"
$c += ""
$c += "final appRouterProvider = Provider<GoRouter>((ref) {"
$c += "  final listener = _AuthRouterListener(ref);"
$c += ""
$c += "  return GoRouter("
$c += "    initialLocation: '/splash',"
$c += "    refreshListenable: listener,"
$c += "    debugLogDiagnostics: true,"
$c += "    routes: ["
$c += "      GoRoute("
$c += "        path: '/splash',"
$c += "        builder: (_, __) => const SplashScreen(),"
$c += "      ),"
$c += "      GoRoute("
$c += "        path: '/login',"
$c += "        builder: (_, __) => const LoginScreen(),"
$c += "      ),"
$c += "      GoRoute("
$c += "        path: '/signup',"
$c += "        builder: (_, __) => const SignUpScreen(),"
$c += "      ),"
$c += "      GoRoute("
$c += "        path: '/dashboard',"
$c += "        builder: (_, __) => const DashboardPlaceholderScreen(),"
$c += "      ),"
$c += "    ],"
$c += "    redirect: (context, gstate) {"
$c += "      final auth = ref.read(authNotifierProvider);"
$c += "      final loc = gstate.matchedLocation;"
$c += ""
$c += "      final isAuthRoute = loc == '/login' || loc == '/signup';"
$c += "      final isSplash = loc == '/splash';"
$c += ""
$c += "      if (auth is AuthInitial || auth is AuthLoading) {"
$c += "        return isSplash ? null : '/splash';"
$c += "      }"
$c += "      if (auth is AuthAuthenticated) {"
$c += "        if (isAuthRoute || isSplash) return '/dashboard';"
$c += "        return null;"
$c += "      }"
$c += "      // Unauthenticated ou Error"
$c += "      if (isAuthRoute) return null;"
$c += "      return '/login';"
$c += "    },"
$c += "  );"
$c += "});"
WriteDart "$ROUTER\app_router.dart" $c

# ================================================================
# 5) MAIN.DART + APP.DART
# ================================================================
Log "" "White"
Log "[5/5] Atualizando main.dart e criando app.dart..." "Yellow"

# ---- app.dart ----
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += "import 'package:flutter_riverpod/flutter_riverpod.dart';"
$c += ""
$c += "import 'core/theme/app_theme.dart';"
$c += "import 'presentation/router/app_router.dart';"
$c += ""
$c += "class DinDinApp extends ConsumerWidget {"
$c += "  const DinDinApp({super.key});"
$c += ""
$c += "  @override"
$c += "  Widget build(BuildContext context, WidgetRef ref) {"
$c += "    final router = ref.watch(appRouterProvider);"
$c += "    return MaterialApp.router("
$c += "      title: 'DinDinVani&Nani',"
$c += "      debugShowCheckedModeBanner: false,"
$c += "      theme: AppTheme.light(),"
$c += "      darkTheme: AppTheme.dark(),"
$c += "      routerConfig: router,"
$c += "    );"
$c += "  }"
$c += "}"
WriteDart "$LIB\app.dart" $c

# ---- main.dart ----
$c = @()
$c += "import 'package:flutter/material.dart';"
$c += "import 'package:flutter_dotenv/flutter_dotenv.dart';"
$c += "import 'package:flutter_riverpod/flutter_riverpod.dart';"
$c += "import 'package:supabase_flutter/supabase_flutter.dart';"
$c += ""
$c += "import 'app.dart';"
$c += ""
$c += "Future<void> main() async {"
$c += "  WidgetsFlutterBinding.ensureInitialized();"
$c += ""
$c += "  // Carrega variaveis de ambiente"
$c += "  await dotenv.load(fileName: '.env');"
$c += ""
$c += "  // Inicializa Supabase"
$c += "  await Supabase.initialize("
$c += "    url: dotenv.env['SUPABASE_URL'] ?? '',"
$c += "    anonKey: dotenv.env['SUPABASE_ANON_KEY'] ?? '',"
$c += "  );"
$c += ""
$c += "  runApp(const ProviderScope(child: DinDinApp()));"
$c += "}"
WriteDart "$LIB\main.dart" $c

# ================================================================
# ANALYZE
# ================================================================
Log "" "White"
Log "================================================================" "Cyan"
Log "Executando flutter analyze..." "Cyan"
Log "================================================================" "Cyan"

Push-Location $BASE
flutter analyze
$exitCode = $LASTEXITCODE
Pop-Location

# Contagem
$provCount = (Get-ChildItem $PROVIDERS -Filter "*.dart" -ErrorAction SilentlyContinue).Count
$scrCount = (Get-ChildItem $SCREENS -Filter "*.dart" -ErrorAction SilentlyContinue).Count
$wdgCount = (Get-ChildItem $WIDGETS -Filter "*.dart" -ErrorAction SilentlyContinue).Count

Log "" "White"
Log "================================================================" "Cyan"
Log " RESUMO" "Cyan"
Log "================================================================" "Cyan"
Log ("Providers:    " + $provCount) "Gray"
Log ("Screens:      " + $scrCount) "Gray"
Log ("Widgets:      " + $wdgCount) "Gray"
Log "Router:       1" "Gray"
Log "main.dart:    atualizado" "Gray"
Log "app.dart:     criado" "Gray"

if ($exitCode -eq 0) {
    Log "" "White"
    Log "SCRIPT 20 - SUCESSO TOTAL" "Green"
    Log "" "White"
    Log "Para testar:" "Cyan"
    Log "  cd Z:\AppFinancas\app" "Gray"
    Log "  flutter run -d chrome" "Gray"
} else {
    Log "" "White"
    Log "SCRIPT 20 - Concluido com avisos/erros (ver acima)" "Yellow"
}
